### ISSUE TITLE
Missing textures - vanilla blocks

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#1]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the bug**    
The following vanilla blocks have missing textures when the mod resourcepack is not loaded:    
- [x] Grass
- [x] Block of Gold
- [x] Ice
- [x] Light weighted pressure plate
- [x] Tall grass
- [x] Water bucket
- [x] Eye of ender
- [x] Prismarine shard

**Comment by HIPPOKLEIDES** [comment]
With just mod resources and virtual assets these vanilla blocks have the appropriate conquest textures in build 28
