### ISSUE TITLE
River Bug- Weird holes in banks

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#10]
**Mod Version & Build Number**    
TerraForged-0.0.1-ALPHA-9-mc1.15.1

**Forge Version**    
forge-1.15.1-30.0.8

**Describe the bug**    
Streams have weird holes/spaces in the banks.

![2020-01-17_13 14 39](https://user-images.githubusercontent.com/33978024/72609530-dcdcf080-392d-11ea-82d5-095ac68b8195.png)
![2020-01-17_13 14 55](https://user-images.githubusercontent.com/33978024/72609531-dd758700-392d-11ea-977f-9b81d44d8673.png)
![2020-01-17_13 15 04](https://user-images.githubusercontent.com/33978024/72609532-dd758700-392d-11ea-9f30-7a641fd08dc9.png)

**Comment by dags-** [comment]
These are 'wetland pools' - they occur (sometimes) where climate moisture values are high and the terrain height is close to water level.

When we have more biome variations added you'll typically find these areas decorated as marshes etc
Vanilla only has a few appropriate biomes in jungles and swamps which both occur in higher temperature climates.

**Comment by CreativeRealms** [comment]
> These are 'wetland pools' - they occur (sometimes) where climate moisture values are high and the terrain height is close to water level.
> 
> When we have more biome variations added you'll typically find these areas decorated as marshes etc
> Vanilla only has a few appropriate biomes in jungles and swamps which both occur in higher temperature climates.

It's not the pools themselves that are the problem but more how they carve into the ground but don't affect the river depth at all which makes it look really weird.

**Comment by dags-** [comment]
Ah gotcha. Suppose the sand lines emphasize that too.
 
I think the pools only cut away if the terrain height is above water level, so where they come into proximity with river-beds you get that obvious border. I can't remember my reasoning for them behaving that way...
