### ISSUE TITLE
Block Glitch

### ISSUE THREAD

**Issue by Bel26** [Conquest-Reforged/Indev#100]
ConquestReforged-mc1.15.2-4.0.0-v0.1.jar

**Forge Version**    
1.15.2

Spruce Log Stairs and Oak log stair revert to basic spruce and oak stair when placed and a corner.  

![2020-03-06_10 01 43](https://user-images.githubusercontent.com/61890912/76128224-93696300-5fb8-11ea-94e6-8cddb0777ce5.png)
![2020-03-06_10 02 34](https://user-images.githubusercontent.com/61890912/76128231-96fcea00-5fb8-11ea-82be-671fbe644fcb.png)

----

Polychorome Corinthian Capital is transparent underneath when place on a single block.  

![2020-03-02_14 41 18](https://user-images.githubusercontent.com/61890912/76128159-65841e80-5fb8-11ea-9193-fddd75288f70.png)
![2020-03-02_14 41 38](https://user-images.githubusercontent.com/61890912/76128161-69b03c00-5fb8-11ea-82d1-d1a058283024.png)

**Comment by HIPPOKLEIDES** [comment]
The Corinthian capitals definitely shouldn't have been culling like that. I've fixed this for the next version.

I don't think we'll add unique corners for those two step/stair blocks for the time being. In any case, I've added inner/outer corner models for the dark spruce plank steps.
