### ISSUE TITLE
Mooshroom Vanilla Texture

### ISSUE THREAD

**Issue by Avidjabber** [Conquest-Reforged/Indev#101]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.1.jar
Resource Pack downloaded fresh on 03/08/2020

**Forge Version**    
Release 1.15.2-forge-31.1.18

**Describe the bug**    
The Mooshroom still seems to be using vanilla textures except for the mushrooms on it's back. Occasionally, when using the spawn egg, it spawns a random missing texture as well as the mooshroom.

**Screenshots/Video**    
![mooshroom](https://user-images.githubusercontent.com/61600445/76164665-a72ed980-611e-11ea-9bdf-03d223dea433.png)

**System Information (optional)**    
Total RAM: 16 GB
Allocated RAM: 8GB
CPU: Intel I5-6300HQ 2.30GHz
GPU: NVidia GeForce GTX 960M

**Comment by ArtemisiaTR** [comment]
Fixed
