### ISSUE TITLE
Plants sometimes place down missing textures.

### ISSUE THREAD

**Issue by Avidjabber** [Conquest-Reforged/Indev#102]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.1.jar
Resource Pack downloaded fresh on 03/08/2020

**Forge Version**    
1.15.2-forge-31.1.18

**Describe the bug**    
Sometimes while placing plants, a missing texture will appear instead of the plant. 

**Screenshots/Video**    
![plant issue](https://user-images.githubusercontent.com/61600445/76164738-2de3b680-611f-11ea-8b1f-e01f00010359.png)
![plant issue 2](https://user-images.githubusercontent.com/61600445/76164741-31773d80-611f-11ea-9f8e-8b3bc808e2b3.png)

**System Information (optional)**    
Total RAM: 16 GB
Allocated RAM: 8GB
CPU: Intel I5-6300HQ 2.30GHz
GPU: NVidia GeForce GTX 960M

**Comment by CreativeRealms** [comment]
More broken stuff https://youtu.be/_F6y5WwudrE

**Comment by dags-** [comment]
Have you tweaked any of the forge settings in it's config by chance?

**Comment by CreativeRealms** [comment]
I did actually. Totally forgot about it.

**Comment by CreativeRealms** [comment]
Set alwaysSetupTerrainOffThread to true.

**Comment by CreativeRealms** [comment]
Everything seems to be fixed.
