### ISSUE TITLE
Potential Hawthorn Bush Texture Glitch

### ISSUE THREAD

**Issue by Avidjabber** [Conquest-Reforged/Indev#103]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.1.jar
Resource Pack downloaded fresh on 03/08/2020

**Forge Version**    
1.15.2-forge-31.1.18

**Describe the bug**    
The Hawthorn Bush texture appears to have random white pixels on it. Not sure if this is intended or not.

**Screenshots/Video**    
![hawthorn bush white flecks](https://user-images.githubusercontent.com/61600445/76164836-03dec400-6120-11ea-9ee4-508b0d284716.png)

**System Information (optional)**    
Total RAM: 16 GB
Allocated RAM: 8GB
CPU: Intel I5-6300HQ 2.30GHz
GPU: NVidia GeForce GTX 960M

**Comment by HIPPOKLEIDES** [comment]
Good catch, should be fixed in the next version!
