### ISSUE TITLE
Better Animals Plus Mob Spawning

### ISSUE THREAD

**Issue by Inactivememe** [Conquest-Reforged/Indev#104]
**ConquestReforged-3.0.2-mc1.12.2.jar, betteranimalsplus-1.12.2-8.2.0.jar **    

**1.12.2-forge1.12.2-14.23.5.2847**    

**The animals from betteranimalsplus do not seem to spawn anywhere, I have searched very far and not found a single one. If you are in creative you can spawn them, but they do not spawn on their own.**    

**System Information**    
Total RAM: 32   
Allocated RAM: 12
CPU: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz  3.10GHz   
GPU: NVIDIA GeForce RTX 2080 Ti

**Not sure if this is helpful or not but it seems the betteranimalmodels mod(same creator) does work, as all it really does is replace old models**

**Comment by dags-** [comment]
Oh sorry, I directed you here but didn't realise you were talking about 1.12. Assumed 1.15 due to being patron. My bad!

We'll keep in mind mob-spawning when we get that far with 1.15 though
