### ISSUE TITLE
Redstone not working with partial slabs

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#105]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
31.1.0

**Describe the bug**    
Redstone power doesnt seem to pass to an iron trapdoor adjacent to a partial block (vertical and horizontal slab). Below you can see screenshots of a vertical slab (not powered) and a full block (powered - normal)

**Crash Log**    
No crash

**Screenshots/Video**    
Doesnt work on slab
![2020-03-30_18 46 13](https://user-images.githubusercontent.com/36215122/77969448-bc2f0080-72b7-11ea-80be-4be1f67a4851.png)

Works on full block (as it always did)
![2020-03-30_18 46 32](https://user-images.githubusercontent.com/36215122/77969340-7ffba000-72b7-11ea-8ea7-ca0a2ac9f3c6.png)

**System Information (optional)**    
Total RAM:    24
Allocated RAM: 12
CPU:  Intel i5-7300HQ @2.50GHz
GPU: Nvidia GeForce GTX 1050

**Additional context**    
I was gonna make a basic trapdoor/lever contraption on a on a huge furnace/oven. Noticed the bug when the lever placed behind a vertical slab didnt have any effect. It's next to the bellows on the left side of the chimney.

![2020-03-30_18 58 41](https://user-images.githubusercontent.com/36215122/77969820-aa9a2880-72b8-11ea-81e3-44365d9df969.png)

**Comment by HIPPOKLEIDES** [comment]
![2020-03-30_16 45 33](https://user-images.githubusercontent.com/31572523/77972341-ed9ed080-72a5-11ea-940e-e4957108d8e3.png)
This seems to be a vanilla mechanic, as you can see from the redstone power not passing through the vanilla cobblestone stair, so this should be working as intended.
