### ISSUE TITLE
Bucket connects to walls/fences

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#106]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
31.1.30

**Describe the bug**    
The `conquest:empty_bucket` connects to fences like a regular full-block does. 
Perhaps the bucket should be more like a 3/4 Pillar block, both in hit-box size and connecting behavior?

**Crash Log**    
-

**Screenshots/Video**    
![2020-04-02_18 32 41](https://user-images.githubusercontent.com/36215122/78306025-61441600-7510-11ea-8073-3093b089db27.png)

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
Good catch. This is fixed for the empty_bucket block and many others of the same class.
