### ISSUE TITLE
Dark Oak door top and bottom parts not aligned

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#107]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
31.1.30

**Describe the bug** 
The Dark Oak door top and bottom parts are misaligned and we see a gap between them (see photos). When looking up close it looks like the top part is 5 "pixels" thick and the bottom is 6 "pixels" thick.

**Crash Log**    
-
**Screenshots/Video**    
![2020-04-06_15 56 45](https://user-images.githubusercontent.com/36215122/78599512-4844a900-781f-11ea-9a14-0f3778f3138f.png)
![2020-04-06_15 56 56](https://user-images.githubusercontent.com/36215122/78599514-48dd3f80-781f-11ea-8499-18fd48fffe02.png)

**Additional context**    
I tried to play with the debug_stick on the door and could not change anything... Sorry i don't have better leads.

**Comment by HIPPOKLEIDES** [comment]
fixed
