### ISSUE TITLE
`minecraft:coarse_dirt` and `conquest:grassy_dirt` are the same texture

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#108]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
31.1.30

**Describe the bug**    
After updating the Resource Pack from 1.13 (i think) to the one on HIPPOKLEIDES' repo for best 1.15.2 compatibility, the `minecraft:coarse_dirt` (which used to be kind of dirt/gravel mix) now seems very similar to conquest:grassy_dirt. I'm not sure this was intended.

**Crash Log**    
-

**Screenshots/Video**   
Left: `minecraft:coarse_dirt`
Right: `conquest:grassy_dirt`
![2020-04-06_17 30 50](https://user-images.githubusercontent.com/36215122/78607351-e5f2a500-782c-11ea-8ab5-1eb8093de034.png)
 
![2020-04-06_17 30 47](https://user-images.githubusercontent.com/36215122/78607349-e428e180-782c-11ea-8123-3a9ad8105e48.png)

**Additional context**    
Perhaps OF will revert this issue? idk...

**Comment by HIPPOKLEIDES** [comment]
changed coarse dirt to regular dirt texture

**Comment by SamMadeChannel** [comment]
@HIPPOKLEIDES But what about the dirt-gravelly look of the default minecraft:coarse_dirt that did have its reason to exist? Should i assume `conquest:rocky_soil` is the new alternative between regular dirt and gravel?
