### ISSUE TITLE
Elegant doors not transparent

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#109]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
31.1.30

**Describe the bug**    
Both `conquest:elegant_birch_door` and `conquest:elegant_oak_door` have black "windows" (instead of transparent) when placed. The item itself however (in hand) does show a transparent window, as do the item in the inveantory.

**Screenshots/Video**    
![2020-04-09_18 37 58](https://user-images.githubusercontent.com/36215122/78946774-9cef5a80-7a91-11ea-8ecb-d8463bf32865.png)

**Additional context**    
-

**Comment by HIPPOKLEIDES** [comment]
Fixed, doors have correct rendering now
