### ISSUE TITLE
River  Bug - River cuts through village

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#11]
**Mod Version & Build Number**    
TerraForged-0.0.1-ALPHA-9-mc1.15.1

**Forge Version**    
forge-1.15.1-30.0.8

**Describe the bug**    
River cuts through village.

![2020-01-17_13 10 13](https://user-images.githubusercontent.com/33978024/72609642-2594a980-392e-11ea-9bb1-2dd214f16191.png)

**Comment by dags-** [comment]
More 'Village piece placed on river' - this is expected behaviour for villages
