### ISSUE TITLE
Inverted names/textures for Blue Beaver Tail Roofing

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#110]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
31.1.30

**Describe the bug**    
The names (or textures) for Blue Clay Beaver Tail and Dirty Blue Clay Beaver Tail are inverted. The dirty variant is clean and the other is weathered. They are set to `minecraft:light_blue_terracotta` and `minecraft:blue_terracotta` respectively.

**Crash Log**    
-

**Screenshots/Video**    
The left one is the one called "Blue Clay Beaver Tail" and the right one is the one called "Dirty Blue Clay Beaver Tail".
![2020-04-15_19 44 44](https://user-images.githubusercontent.com/36215122/79399738-23081700-7f52-11ea-82e9-0ad2d71f9286.png)

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed
