### ISSUE TITLE
Oak Wood Plank partial block issue

### ISSUE THREAD

**Issue by ItsCestial** [Conquest-Reforged/Indev#111]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
1.15.2 Version 31.1.0

**Describe the bug**    
All of the Oak Wood Plank variants with the new mechanics turn into Oak Wood when made into full block

**Screenshots/Video**    
![image](https://user-images.githubusercontent.com/38892324/79525689-5c0abf00-8018-11ea-86a2-36f47a1fa4f6.png)

**Comment by HIPPOKLEIDES** [comment]
fixed. thanks!
