### ISSUE TITLE
All Stripped Logs partial block issue

### ISSUE THREAD

**Issue by ItsCestial** [Conquest-Reforged/Indev#112]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.2

**Forge Version**    
1.15.2 Version 31.1.0

**Describe the bug**    
All Stripped Log variants with new mechanics turn into the "Beam Wall" version of their respective block when made into a full block

**Screenshots/Video**    
![image](https://user-images.githubusercontent.com/38892324/79526086-5a8dc680-8019-11ea-9077-baeffe72186a.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
