### ISSUE TITLE
Floating book has no book

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#113]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-155

**Screenshots/Video**    
![2020-04-17_08 08 34](https://user-images.githubusercontent.com/33978024/79536807-93fe1a80-8089-11ea-8c2e-bf1b8fb28dbc.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
