### ISSUE TITLE
Create modded item frame to fix transparency issues.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#114]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-155

**Screenshots/Video**    
![2020-04-17_08 54 11](https://user-images.githubusercontent.com/33978024/79536876-babc5100-8089-11ea-8ec7-4ab89c390b2f.png)

**Comment by HIPPOKLEIDES** [comment]
There are plenty of ways to accomplish this without item frames. For example: 

`/summon minecraft:armor_stand ~ ~ ~ {Invisible:1,ArmorItems:[{},{},{},{id:"conquest:schist_dragon_head,Count:1}]}`

This is even more flexible than item frames, as you can get any "pose" for the "head" (or wherever your block item entity is placed, I've placed mine at the head). This means there's an endless array of different rotations you can get.

Moreover, it doesn't make sense to spend time maintaining the feature of a duplicate item frame when the desired functionality is already in Vanilla Minecraft.

**Comment by Monsterfisch** [comment]
I also created a fix for it in the 1.16 pack
