### ISSUE TITLE
Add Conquest item texture to paintings and add them to creative tabs.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#115]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-155

**Screenshots/Video**    
<img width="486" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/79536976-ef300d00-8089-11ea-8c1e-b847c5547b48.png">

**Comment by HIPPOKLEIDES** [comment]
Texture changed and they're all in the decorations tab now
