### ISSUE TITLE
Fancy Oak Door looks the same as Oak Door when placed

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#116]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.3

**Forge Version**    
31.1.30

**Describe the bug**    
`conquest:oak_door` and `conquest:fancy_oak_door` have the same look when placed, ie the fancy doors has no window like the item has.

**Crash Log**    
-

**Screenshots/Video**    
Left: `conquest:oak_door` (no window, metal hinge - expected)
Right: `conquest:fancy_oak_door` (should have a window and nice carvings)
![2020-04-18_17 30 03](https://user-images.githubusercontent.com/36215122/79671810-525d9480-819b-11ea-9160-b1a4e60af242.png)

**Additional context**    
-

**Comment by HIPPOKLEIDES** [comment]
fixed
