### ISSUE TITLE
Pile of Rope Slab turns to Limestone Cobble.

### ISSUE THREAD

**Issue by Silthulhu** [Conquest-Reforged/Indev#117]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-157

**Forge Version**    
forge-1.15.2-31.1.47

**Describe the bug**    
Pile of Rope Slab turns into Limestone Cobble when the final layer is placed

**Screenshots/Video**    
Attached.
![ropeslabissue](https://user-images.githubusercontent.com/57784733/80021096-242adc80-852e-11ea-92fd-2ce85ed2aa40.gif)

**Comment by HIPPOKLEIDES** [comment]
fixed
