### ISSUE TITLE
Waterfall/Cloud Interraction Rendering Bug

### ISSUE THREAD

**Issue by Hearthseeker** [Conquest-Reforged/Indev#118]
**1.15.2-4 Build #006**    
ConquestReforged-mc1.15.2-4.0.0-v0.3

**Forge Version**    
1.15.2-forge-31.1.0 (Also asked Monster to replicate in his version, as I know forge-51 is also out.)

**Describe the bug**    
If you place the thick or thin cloud in front of the new animated waterfall block, it renders the waterfall block as invisible,
https://i.imgur.com/oRTGzDL.png

**Additional context**    
White cloud block doesn't seem to create this issue

**Comment by HIPPOKLEIDES** [comment]
fixed
