### ISSUE TITLE
Pig does not attach to wood beam like it used to

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#119]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-optiforgecompat

**Forge Version**    
31.1.63

**Describe the bug**    
Placed the `conquest:pig_on_a_spit` decoration block between back-facing wooden vertical supports. However, the fence-like delicious animal block did not connect to the wooden beam's backside, leaving the texture a bit awkwardly rendered. IIRC, in 1.12.2 that contraption was used to make a stand for the pig on a spit.

**Crash Log**    
-

**Screenshots/Video**    
In the first picture, the contraption mentioned : beam, pig, pig, beam
![2020-05-02_13 27 25](https://user-images.githubusercontent.com/36215122/80871252-b000df00-8c79-11ea-868d-4b2aed91da28.png)

In the second one, what was expected (had to use full blocks to make sure the pig would attach on the full block's side:
![2020-05-02_13 34 30](https://user-images.githubusercontent.com/36215122/80871233-aaa39480-8c79-11ea-87cc-f8c77d7753cf.png)

**Additional context** 
-

**Comment by SamMadeChannel** [comment]
FYI, yes been running the OF-compatible version but i had the issue before a few weeks back when OF compatibility was still just a dream!

**Comment by HIPPOKLEIDES** [comment]
I would say this one is best left for the debug stick to fix
