### ISSUE TITLE
Critical Bug - Structures not spawning properly

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#12]
**Mod Version & Build Number**    
TerraForged-0.0.1-ALPHA-9-mc1.15.1

**Forge Version**    
forge-1.15.1-30.0.8

**Describe the bug**    
Some structures do not spawn in the proper biome.

![2020-01-17_13 02 48](https://user-images.githubusercontent.com/33978024/72609776-70162600-392e-11ea-9bb0-d8a19c017bc9.png)
![2020-01-17_13 12 45](https://user-images.githubusercontent.com/33978024/72609778-70162600-392e-11ea-9b3b-38cc591579d4.png)

**Comment by dags-** [comment]
I believe I've fixed this as of TF builds 15 and above.

The issue was that the structure placement logic was using the vanilla biome provider to determine where biomes are rather than TF's, so it'd often pick wholly inappropriate locations for them

**Comment by CreativeRealms** [comment]
> I believe I've fixed this as of TF builds 15 and above.
> 
> The issue was that the structure placement logic was using the vanilla biome provider to determine where biomes are rather than TF's, so it'd often pick wholly inappropriate locations for them

Looks like it's fixed.
