### ISSUE TITLE
Weird wall and horizontal beams rendering causing see-through effect

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#120]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-optiforgecompat

**Forge Version**    
31.1.63

**Describe the bug**    
When placing fences and support beams, it often does not render properly or we get to see through the block behind it. I've encountered the issue with the palm board and horizontal beams mostly. 

**Crash Log**    
-

**Screenshots/Video**    
Here you can see one side of the pal board not rendering while, when looking from inside, it renders well.
![2020-05-02_13 44 00](https://user-images.githubusercontent.com/36215122/80871555-4eda0b00-8c7b-11ea-9ae9-d36bb2c2860c.png)

Below are examples of the horizontal beam allowing to see thru the block behind it:
![2020-05-02_13 39 47](https://user-images.githubusercontent.com/36215122/80871576-6618f880-8c7b-11ea-8a7d-1bcd390656cc.png)
![2020-05-02_13 40 22](https://user-images.githubusercontent.com/36215122/80871578-687b5280-8c7b-11ea-806b-b1fb600ed568.png)

**Additional context**    
It's similar to the issue i've reported with column capitals and bases on the wrong git repo before (i believe that was the RP's repo).
![2020-03-06_23 37 00](https://user-images.githubusercontent.com/36215122/80871552-4aaded80-8c7b-11ea-99ed-2ee346f690c5.png)

**Comment by HIPPOKLEIDES** [comment]
Fixed. Horizontal beams have their own hitboxes now too
