### ISSUE TITLE
Ship_Lantern Bug (not working correctly)

### ISSUE THREAD

**Issue by Thregollas** [Conquest-Reforged/Indev#122]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.41

**Forge Version**    
forge-1.15.2-31.1.0-installer

**Describe the bug**    
It seems like the block named Ship_lantern is not working correctly without but when shader (Sildurs Vibrant Shaders v1.22 Extreme-VL) is on, the lantern is working correctly and its visible. A view will be provided with 2 pictures below.

**Screenshots/Video**    
![image](https://user-images.githubusercontent.com/25563766/80985215-94433780-8e37-11ea-94a6-9a9b7f3fae6f.png)
![image](https://user-images.githubusercontent.com/25563766/80985412-de2c1d80-8e37-11ea-920d-aa97bdd2d6af.png)

**Additional context**    
It looks like shader (Sildurs Vibrant Shaders v1.22 High) seems to make the block to be visible too.

**Comment by HIPPOKLEIDES** [comment]
You're using an insanely old version of CR. With Optifine 1.15.2_HD_U_G1_pre15, forge 32.1.63, and the latest alpha the ship lantern is fine for me.
