### ISSUE TITLE
New Red Asian Window has broken CTM

### ISSUE THREAD

**Issue by Silthulhu** [Conquest-Reforged/Indev#123]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.41

**Forge Version**    
Forge 31.1.74

**Describe the bug**    
The new red Asian Window has a broken CTM, connects in a way that won't make sense in a build. 

**Screenshots/Video**    
![2020-05-05_19 30 05](https://user-images.githubusercontent.com/57784733/81062200-abfae880-8f29-11ea-96e0-c37ee2ab3e48.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
