### ISSUE TITLE
Copy issue with "marble_plinth_vertical_slab" by using worldedit

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#126]
**Mod Version & Build Number (of both mods)**    
worldedit-forge-mc1.15.2-7.1.0
WorldEdit-CUI-FE3-1.15.2-3.0.4
ConquestReforged-mc1.15.2-4.0.0-v0.41

**Forge Version**    
Forege 31.163

**Describe the Compatibility Issue**    
When the copied content contains marble_plinth_vertical_slab, the copy is incomplete.

**Crash Log**    
No crash but the issue

**Screenshots/Video**    
First time using this,don't know how to upload.It could be seen at the discord"patron".

**Comment by HIPPOKLEIDES** [comment]
![](https://cdn.discordapp.com/attachments/344513828685348865/716260421967020052/ZBU1LX_WO92Y43BDEFTX.png)

For reference

The block is designed to not have the property "north", so that on it's own isn't an issue.
Besides throwing an error message, what's the problem?

**Comment by WhiteWindXX** [comment]
If the selected range contains this block, you cannot copy all the blocks in the range to another location.You can view the image attached to the email. On the left is the copy source and on the right is the copy result.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HIPPOKLEIDES"<notifications@github.com&gt;; 
发送时间: 2020年5月31日(星期天) 凌晨4:41
收件人: "Conquest-Reforged/Indev"<Indev@noreply.github.com&gt;; 
抄送: "じ☆追风☆じ"<834576351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Conquest-Reforged/Indev] Copy issue with &quot;marble_plinth_vertical_slab&quot; by using worldedit (#126)





 

 
For reference
 
The block is designed to not have the property "north", so that on it's own isn't an issue.
 Besides throwing an error message, what's the problem?

**Comment by WhiteWindXX** [comment]
Tried to send pic in email but failed.Like I said,if I copied a range containing this block,the result would be incomplete(i.e.,the block could not be copied,and a large number of other blocks would be lost)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HIPPOKLEIDES"<notifications@github.com&gt;; 
发送时间: 2020年5月31日(星期天) 凌晨4:41
收件人: "Conquest-Reforged/Indev"<Indev@noreply.github.com&gt;; 
抄送: "じ☆追风☆じ"<834576351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Conquest-Reforged/Indev] Copy issue with &quot;marble_plinth_vertical_slab&quot; by using worldedit (#126)





 

 
For reference
 
The block is designed to not have the property "north", so that on it's own isn't an issue.
 Besides throwing an error message, what's the problem?

**Comment by HIPPOKLEIDES** [comment]
Tested with latest 1.15.2 worldedit and did not experience any issues
