### ISSUE TITLE
Walls don't connect to each other.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#128]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-206

**Screenshots/Video**    
![2020-06-01_22 22 36](https://user-images.githubusercontent.com/33978024/83445930-88f32400-a456-11ea-9fd1-a7928f93f826.png)

**Comment by HIPPOKLEIDES** [comment]
Working again.

For future reference, if you find walls that don't connect, walls are whitelisted for connections in  `assets/data/minecraft/tags/blocks/walls`

If a wall is removed and its entry in there isn't removed/changed, it will break all walls.

This enables Vanilla and cross-mod compatibility for wall connections
