### ISSUE TITLE
Terrain Bug - Floating red sand spawning over caves

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#13]
**Mod Version & Build Number**    
TerraForged-0.0.1-ALPHA-9-mc1.15.1

**Forge Version**    
forge-1.15.1-30.0.8

**Describe the bug**    
Floating red sand spawning over caves. When used with CR the red sand is replaced with floating concrete powder stairs.

![2020-01-17_13 15 59](https://user-images.githubusercontent.com/33978024/72609932-ce430900-392e-11ea-84a0-88045f03e67e.png)

**Comment by dags-** [comment]
It's actually that the caves are carved after the sand is placed, but they don't consider blocks like sand/clay/gravel as materials they need to remove for whatever reason (I seem to vanilla players having a huge boner for sharing seeds with huge sand-drop-traps at spawn or something?)

Picking up stairs (and basically any other non-cube) as a world gen block is a separate issue that I need to work on.

**Comment by dags-** [comment]
I'm testing a possible fix for this which is available in builds +25.

Basically, vanilla's cave carvers hard-code the blockstates that are deemed as 'carvable' so I've tried adding in a step in-between that converts the blocks that the carver 'sees' into the closest equivalent carvable type (red_sand to sand, for example).
