### ISSUE TITLE
Scaffolding doesn't have CTM and should have more variants instead of biome specific textures.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#130]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-206

**Screenshots/Video**    
![2020-06-01_22 26 44](https://user-images.githubusercontent.com/33978024/83446261-12a2f180-a457-11ea-92b9-b497f2afbc70.png)

**Comment by HIPPOKLEIDES** [comment]
done
