### ISSUE TITLE
Use CTM for yellow plaster window instead of four blocks.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#131]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-206

**Screenshots/Video**    
![2020-06-01_22 28 26](https://user-images.githubusercontent.com/33978024/83446461-5f86c800-a457-11ea-9cc6-4bed96be79b8.png)

**Comment by HIPPOKLEIDES** [comment]
removed those blocks and made those textures ctm
