### ISSUE TITLE
Mirror texture is broken.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#133]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-206

**Screenshots/Video**    
![2020-05-29_06 03 22](https://user-images.githubusercontent.com/33978024/83446774-f489c100-a457-11ea-8e65-11becb300230.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
