### ISSUE TITLE
Large clay pot item model scale

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#134]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-206

**Screenshots/Video**    
![2020-06-01_22 34 18](https://user-images.githubusercontent.com/33978024/83446850-1be08e00-a458-11ea-920a-2547f7dad052.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
