### ISSUE TITLE
Dead corals losing texture

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#139]
If you place coral on the ground without water,wait for seconds,it turns apurple and black block(Just like losing texture)instead of a white one(dead coral).
Fire coral for example
![2HLRXQG37Q`5}S X@3}IMRG](https://user-images.githubusercontent.com/66167634/83517323-49d2da80-a50b-11ea-8dcc-24c531a4f370.png)
![ULJZY 4UV5)O0MA_3 HT5MQ](https://user-images.githubusercontent.com/66167634/83517335-4ccdcb00-a50b-11ea-841b-f2273c4c7281.png)
Using forge: forge 31.1.63
Using resourcepack version:ConquestRefogedRP-ALPHA-24
Using mod version:ConquestReforged-mc1.15.2-4.0.0-v0.41
Using optifine version:previewOptiFine_1.15.2_HD_U_G1_pre19

**Comment by HIPPOKLEIDES** [comment]
fixed
