### ISSUE TITLE
Losing particle effect texture when blocks is broken

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#140]
Particle effect texture is lost when rustic_fence is broken
Particle effect texture is lost when Wicker_Fence, Wicker_Fence_half, Staright_wicker_fence, Staright_wicker_fence_half is broken.(When they are placed alone)
![95B}1@ZRHQ%8Z`I`436HVWA](https://user-images.githubusercontent.com/66167634/83518027-7c310780-a50c-11ea-8533-3932a0208f2b.png)
![H3)2IM3PDIEWFS~}OJXTYIS](https://user-images.githubusercontent.com/66167634/83518035-805d2500-a50c-11ea-9253-cff1af2c50f2.png)

Using forge: forge 31.1.63
Using resourcepack version:ConquestRefogedRP-ALPHA-24
Using mod version:ConquestReforged-mc1.15.2-4.0.0-v0.41
Using optifine version:previewOptiFine_1.15.2_HD_U_G1_pre19

**Comment by HIPPOKLEIDES** [comment]
fixed
