### ISSUE TITLE
Transparent texture of Composter、Marble_cornice and Sandstone_cornice

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#141]
When there is block next to the composter, the side next to the composter becomes transparent.
When place a pillar on the Marble_cornice and sandstone_cornice,the top of their texture will become transparent.
![GB8TWAHN8%2~%@WKS41LFOH](https://user-images.githubusercontent.com/66167634/83518262-ce722880-a50c-11ea-8a3b-2f31d12d663b.png)
![5R71(YPN E(CXZY WSN AX](https://user-images.githubusercontent.com/66167634/83518274-d3cf7300-a50c-11ea-8777-ded3654b7183.png)

Using resourcepack version:ConquestRefogedRP-ALPHA-24
Using mod version:ConquestReforged-mc1.15.2-4.0.0-v0.41
Using forge version: forge 31.1.63
Using optifine:previewOptiFine_1.15.2_HD_U_G1_pre19

**Comment by HIPPOKLEIDES** [comment]
should be fixed
