### ISSUE TITLE
Waterlogged state for Rice

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#142]
**Describe your suggestion**    
Add waterlogged state for RICE.

**Explain why you think your suggestion should be added**    
Rice grows in water,it looks more realistic.

If that can't be done , so be it.It's OK for now.

**Comment by HIPPOKLEIDES** [comment]
Since our farmland layers can be waterlogged and our crop blocks are lowered to be level with layers now, I don't think this is necessary
