### ISSUE TITLE
Visual error on moss

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#145]
When place a block right next to them(north、south、west、east），they will appear a weird cross line at the top.might be the issue with the connecting texture
These are the issue blocks
reindeer_lichen
elegant_sunburst_lichen
red_sphagnum_moss
yellow_sphagnum_moss
dark_green_sphagnum_moss

ConquestReforged-mc1.15.2-4.0.0-v0.41
Forge:Forge 31.1.63
preview_OptiFine_1.15.2_HD_U_G1_pre23
ConquestRefogedRP-ALPHA-26
**Screenshots/Video**    
![2020-06-08_14 14 41](https://user-images.githubusercontent.com/66167634/83998931-42408500-a994-11ea-861d-0ef4e976427f.png)
![2020-06-08_14 15 03](https://user-images.githubusercontent.com/66167634/83998938-45d40c00-a994-11ea-92ad-f1e2d169c1ea.png)
![2020-06-08_14 15 28](https://user-images.githubusercontent.com/66167634/83998946-49679300-a994-11ea-8a21-f3f02b7bdaa5.png)
![2020-06-08_14 16 11](https://user-images.githubusercontent.com/66167634/83998952-4c628380-a994-11ea-9f44-d7b324cb6421.png)
![2020-06-08_14 16 39](https://user-images.githubusercontent.com/66167634/83998957-508ea100-a994-11ea-95c3-abfebcd199dd.png)

**Comment by HIPPOKLEIDES** [comment]
Good catch. I think I've removed those (there were unnecessary faces in the cross model). Should be fixed in the next release.
