### ISSUE TITLE
Trident bug

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#146]
![2020-06-08_15 29 58](https://user-images.githubusercontent.com/66167634/84004482-35c12a00-a99e-11ea-9ec0-f45a67c6eaea.png)

When holding it.

Forge:31.1.63
ConquestReforged-mc1.15.2-4.0.0-v0.41
preview_OptiFine_1.15.2_HD_U_G1_pre23
ConquestRefogedRP-ALPHA-26

**Comment by HIPPOKLEIDES** [comment]
fixed
