### ISSUE TITLE
Block Picker GUI removes transparency from hotbar when opened (while using the resourcepack).

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#16]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-42-mc1.15.2

**Forge Version**    
1.15.2-forge-31.0.1

**Screenshots/Video**    
![Screenshot_1](https://user-images.githubusercontent.com/33978024/73134675-3043f280-4042-11ea-876d-6210fb59392d.png)

**Comment by dags-** [comment]
Fixed
