### ISSUE TITLE
Large Amphora's Texture Res Higher than 32x.

### ISSUE THREAD

**Issue by ArtemisiaTR** [Conquest-Reforged/Indev#165]
Texture must be reworked to ensure consistency within the mod.
![2020-06-09_19 19 49](https://user-images.githubusercontent.com/29824134/84174189-f28eb600-aa86-11ea-9aad-279ac0d0f9bd.png)

**Comment by Dechoppy** [comment]
Fixed:
- large_amphora uvmapping redone scaled from 64x to 32x

Changes:
- added more variation
