### ISSUE TITLE
Decorations tab name

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#168]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-218

**Screenshots/Video**    
<img width="302" alt="Screenshot_2" src="https://user-images.githubusercontent.com/33978024/84329080-5f3fa880-ab8c-11ea-8c3b-970737e21828.png">

**Comment by HIPPOKLEIDES** [comment]
This was to avoid conflicts with the vanilla "decorations" tab
I've changed it to "Decor"
