### ISSUE TITLE
Ash planks with tudor box frame have a wrong texture

### ISSUE THREAD

**Issue by SovietProIetarian** [Conquest-Reforged/Indev#171]
- 
ConquestReforged-mc1.15.2-4.0.0-v0.5
-
release 1.15.2-forge-31.1.63
-
Ash planks with tudor box frame block has a texture of the Oak planks with tudor box, while the image in the inventory has a proper texture.
-
![ashplanks](https://user-images.githubusercontent.com/66770080/84358452-993a9a00-abe0-11ea-9341-e41d9d52ba4e.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
