### ISSUE TITLE
fancy_marble_balustrade connected texture suggestion

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#173]
Add top and bottom direction connected texture for fancy_marble_balustrade to make the pillar between them look bigger.

**Comment by HIPPOKLEIDES** [comment]
![2020-11-01_10 13 53](https://user-images.githubusercontent.com/31572523/97806700-d8aa6700-1c11-11eb-9828-a542d3c0b792.png)
good suggestion!
