### ISSUE TITLE
Connected texture issue with all the vanilla slab and all the conquest glass pane

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#174]
Take Simple white wooden frame window pane and smooth quartz slab as an example
![2020-06-12_17 01 04](https://user-images.githubusercontent.com/66167634/84486043-67ecc780-accf-11ea-8f9f-a6023925103c.png)

**Comment by HIPPOKLEIDES** [comment]
Related to the mechanic where additional pane faces are generated in the block above so people can make windows with slabs, stairs, arches, etc. Think I'll leave this as is. If you really want to get rid of the extra faces use the debug stick

**Comment by WhiteWindXX** [comment]
But there is no such feature when using conquest block
 
---Original---

**Comment by WhiteWindXX** [comment]
Sorry, get it now
 
---Original---
