### ISSUE TITLE
Layers not working. 

### ISSUE THREAD

**Issue by Avidjabber** [Conquest-Reforged/Indev#177]
**Mod Version & Build Number**    
Alpha build Build #009
AlphaRP build Build #030

**Forge Version**    
31.2.21

**Describe the bug**    
Layers are not working as intended. They appear several layers thick and won't stack properly. I've tried this with several types of dirt and grasses and got the same result on all. 

**Screenshots/Video**    
![aaaaaaaaaaa](https://user-images.githubusercontent.com/61600445/85238284-9ca8ff00-b3f2-11ea-86d4-2f228e517424.png)

**Additional context**    
Optifine Pre 29 was used.

**Comment by CreativeRealms** [comment]
You pressed B which locks the layer type. Press it until you see the number 0 on your screen and it will work properly again.
