### ISSUE TITLE
Shinning texture bug of grass_and_sand

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#178]
If you're a certain distance away from Grass_and_sand almost a chunk (16) away, the texture on it will blink, while the other blocks don't seem to have this problem.
![C_VX%VO~3C$TD@IJX {0_K0](https://user-images.githubusercontent.com/66167634/85254487-02e55e80-b493-11ea-95ad-59f798a2e808.png)
Screenshot in a distance.

By the way i am using Optifine per29,because there is a bug when using per30 that you can't see anything on screen but black and purple texture.

**Comment by HIPPOKLEIDES** [comment]
Removed full blocks for these and added optifine grassy overlays instead
