### ISSUE TITLE
Lots of suggestions

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#179]
**Animals**: snake,frog,crab,small spider,hanging small spider,small spider on web,lizard, chameleon,hedgehog, squirrel.
**Grass:** : lavender(both one block high and two blocks high),thistles with thorns(It slows down and takes damage.）,bamboo fence without crossrope(like 1.12.2).
**Small stuff**: like bird cage、deer's hunting trophy、big piano、baguette basket、mail box and so on.
The addition of a spiral staircase and multi-angle windows is highly recommended.And also two blocks high door
like this
![2020-06-23_16 43 25](https://user-images.githubusercontent.com/66167634/85384910-3ba93480-b574-11ea-9117-5a5d01f7fddb.png)
![2020-06-23_16 43 37](https://user-images.githubusercontent.com/66167634/85384934-45cb3300-b574-11ea-854f-2d0166a85741.png)
![2020-06-23_17 07 07](https://user-images.githubusercontent.com/66167634/85384950-49f75080-b574-11ea-8c34-1e7f9cb02930.png)

These critters can liven up the environment.For example, they can be used in fields, in forests and even in house and so on.
The combination of lavender and tulips can make Dutch architecture (windmill architecture) look better!
The thorns are because there are fewer drought-tolerant plants in CR compared to greens, and I think it would be nice to have a more character-possessing (acts like sweet berries) plant.
The bamboo is because I want more color, that's all. It would work if there was a random texture for the bamboo.
Spiral staircase and multi-angle windows  and door could make bulidings more detailed.

Snake could work like tools on the ground.
Frog、crab、lizard,、chameleon、hedgehog,、squirrel can act like toad and rat.
Speaking of spiders, this work perfectly.
![2020-06-23_16 40 45](https://user-images.githubusercontent.com/66167634/85381753-db64c380-b570-11ea-8f85-c66cfad95fef.png)
multi-angle windows could just work like what fence did.

I apologize for making so many suggestions at once, but I truly hope that these will be added to the CR in the future. Hopefully CR will get better and better! By the way, the results so far look really good, you guys are doing a great job!

**Comment by HIPPOKLEIDES** [comment]
Thanks for the suggestions. Definitely have our eye on many of these. Since there are so many, this issue would effectively be open for a very long time, so I'll be closing it
