### ISSUE TITLE
Variant wheel not working for Vanilla blocks that are family parents

### ISSUE THREAD

**Issue by HIPPOKLEIDES** [Conquest-Reforged/Indev#18]
**Mod Version & Build Number**    
Build 053

**Forge Version**    
Whatever the ReforgedMod repo is using

**Describe the bug**    
When pressing C while hovering over a vanilla block (eg: cobblestone), nothing happens. On the other hand, pressing C while hovering over a modded variant of that block (eg: cobblestone arch) shows all the variants, as well as the parent (cobblestone). 

Basically, this makes the variants of blocks like cobblestone pretty inaccessible.

**Comment by dags-** [comment]
Probably related to #19

**Comment by dags-** [comment]
I think the problem was that in FamilyInit, the blocks were added to the Family but were not being registered to the FamilyRegistry.

Hopefully fixed in build `#5`

**Comment by HIPPOKLEIDES** [comment]
This seems to be half fixed. The method "registerRoot" makes families work perfectly, but the method "register" not quite.

At the moment, register gets things working for vanilla variants (eg: cobblestone_slab), but not for the actual parent of the family (eg: cobblestone)

**Comment by dags-** [comment]
Fixed for that method too!
