### ISSUE TITLE
Shulker box toolbar transparency issue

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#181]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-260

**Screenshots/Video**    
<img width="370" alt="Screenshot_4" src="https://user-images.githubusercontent.com/33978024/87449865-67b15600-c606-11ea-9791-78f830088ceb.png">

**Comment by HIPPOKLEIDES** [comment]
![image](https://user-images.githubusercontent.com/31572523/97809145-16ae8780-1c20-11eb-8830-24de654c4ff0.png)
Recreated at one moment and when I looked back it was fixed. In any case this is pretty minor and the rendering of these items is built into Minecraft (as opposed to being models that are stored in json files)
