### ISSUE TITLE
Particles are lost when spruce wood stool is destroyed

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#188]
![2020-08-01_17 27 14](https://user-images.githubusercontent.com/66167634/89098707-87c18180-d41c-11ea-9029-f4a65c1e1d3f.png)
![2020-08-01_17 27 12](https://user-images.githubusercontent.com/66167634/89098708-885a1800-d41c-11ea-84f9-51d105aafbbe.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
