### ISSUE TITLE
Variant Wheel - Variants added to a family in FamilyInit do not show other variants when wheel is opened

### ISSUE THREAD

**Issue by HIPPOKLEIDES** [Conquest-Reforged/Indev#19]
**Mod Version & Build Number**    
Build 053

**Forge Version**    
Whatever the ReforgedMod repo is using

**Describe the bug**    
Some blocks are added to block families in FamilyInit. In the case of the wicker fence, a number of variants are added to its family. When opening the variant wheel for "wicker_fence", all these variants are accessible (as seen in the first picture).

Things go awry when opening the variant wheel for one of these variants of the wicker fence, such as "wicker_fence_thin_vertical_slab". When this is done, none of the other variants or the parent are accessible (as seen in the second picture). 

**Screenshots/Video**    
![](https://cdn.discordapp.com/attachments/636269498445463561/674100675000401921/unknown.png)

![](https://cdn.discordapp.com/attachments/636269498445463561/674100550379372545/unknown.png)

**Comment by dags-** [comment]
Possibly fixed as part of #18 - please test

**Comment by HIPPOKLEIDES** [comment]
Fixed as far as I can tell
