### ISSUE TITLE
Grass block stairs and slab missing texture

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#191]
only happen at bottom
![2020-08-04_22 18 15](https://user-images.githubusercontent.com/66167634/89305040-bcde0600-d6a0-11ea-9512-b6f83f1e14e6.png)

**Comment by HIPPOKLEIDES** [comment]
does it still happen without the shaders or with different shaders?

**Comment by WhiteWindXX** [comment]
> does it still happen without the shaders or with different shaders?

I double checked it, it's not happen anymore.I think that was a optifine issue.But it happen form time to time

**Comment by HIPPOKLEIDES** [comment]
I can't seem to recreate it, and the bottoms are showing up as dirt for me as they should be, so closing
