### ISSUE TITLE
Birch CTM

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#198]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-275

**Screenshots/Video**    
<img width="726" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/89826580-1c378c80-db5f-11ea-9a32-f37362c771d4.png">

**Comment by HIPPOKLEIDES** [comment]
fixed
