### ISSUE TITLE
Missing texture - Ship lantern

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#2]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the bug**    
Ship lantern has a missing texture.

**Comment by HIPPOKLEIDES** [comment]
Feel like it's been a while since we updated that to the latest OBJ format, but it seems to be working in build 27
