### ISSUE TITLE
Item frame transparency

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#201]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-279

<img width="359" alt="Screenshot_8" src="https://user-images.githubusercontent.com/33978024/90344366-ca40ac00-e021-11ea-8c87-634b9408b8ad.png">

**Comment by Eaglestorm13** [comment]
MIne look like this when not using the shader. Thou am curious what setting shader setting changes the looks of it.

**Comment by HIPPOKLEIDES** [comment]
fixed
