### ISSUE TITLE
wooden beam CTM issue

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#203]
When wooden beam placed like this（specific variant and position),the bottom one will lose texture,only happen to wooden beam,other beams don't have this problem.
![2020-08-26_20 55 06](https://user-images.githubusercontent.com/66167634/91332811-51023f80-e7ff-11ea-8b8d-37df0d544d83.png)
the normal one should be like this
![2020-08-26_20 55 11](https://user-images.githubusercontent.com/66167634/91332851-5a8ba780-e7ff-11ea-8339-9656626be118.png)

**Comment by HIPPOKLEIDES** [comment]
should be fixed now as random culling is removed from this model now
