### ISSUE TITLE
[REQUEST] Consider replacing vertical slabs and side-stairs with corner-posts.  Can extend idea for build options.

### ISSUE THREAD

**Issue by DVorriose** [Conquest-Reforged/Indev#204]
**Is your feature request related to a problem? Please describe.**

Inside vertical slabs do not connect on corners.

That is, if you have a 2x2 block space
ABC
DEF
And you put vertical slabs on B and F, you can connect outside slabs with a sideways stair on C, but you cannot connect inside slabs.

**Describe the solution you'd like**

Replace vertical slabs and stairs with vertical "quarter-posts:"  A post that takes up 1/4th of a block, and which can be placed in any one corner, NW, NE, SE, or SW.

**Describe alternatives you've considered**

You could create a quarter post to connect inside slabs, and keep vertical slabs and sideways stairs, but that also adds to the overall block count.

**Additional context**

Extension possibility 1:  Replace all CR slabs and stairs with vertical and horizontal quarter-posts/logs.  It would take more time (2-3 clicks) for a player to lay slabs or stairs, but they would have more build options:
- off-center beams/trusses/etc
- roofing edges
- off-center trees (or tree parts)

Extension possibility 2:  Allow mixed quarter-posts in the same block space (think "double slabs" mod).

Existing example:  The mod "Misty World" has a partial implementation of this with it's foggy rock and trees.

**Comment by HIPPOKLEIDES** [comment]
These have been added to 1.15 for a while.
