### ISSUE TITLE
Lion Frieze

### ISSUE THREAD

**Issue by phantaC** [Conquest-Reforged/Indev#205]
It would be really cool to have some Frieze blocks for statues and designs, I'm linking one potential design idea below, but there could be a few categories. I think it would also be nice if they are recessed by 1 or 2 pixels or extruded from the block by 1 or 2 since they are often part of pediments and other designs. Thanks, hope you like the idea. 
![Lion side](https://user-images.githubusercontent.com/70549111/91776818-e0b73d80-ebb3-11ea-9902-62cd830a2c24.jpg)
![Lion front](https://user-images.githubusercontent.com/70549111/91776820-e14fd400-ebb3-11ea-8bcd-fdabf082e7a5.jpg)

**Comment by HIPPOKLEIDES** [comment]
Not a bad suggestion. Will keep it in mind for the future as time permits!
