### ISSUE TITLE
Banners not working as intended

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#206]
ConquestReforged-mc1.15.2-4.0.0-v0.72.jar

**Forge Version**    
31.2.36

**Describe the bug**    
Banners not working as you see there is black where a letter should be

**Crash Log**    
If your game crashed please upload a crash log (pastebin.com being the preferred method).

**Screenshots/Video**    
Screen shot added

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**    
I have tried with no CR textures and without shaders

**Comment by Eaglestorm13** [comment]
![2020-09-03_07 21 49](https://user-images.githubusercontent.com/70701092/92116907-10d02d80-edba-11ea-9b8e-c20487ce593c.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
