### ISSUE TITLE
Spruce wood trap door

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#207]
**Is your feature request related to a problem? Please describe.**
Trap door does not match in color to other of its variants

**Describe the solution you'd like**
To match the other Spruce items

**Describe alternatives you've considered**

**Additional context**
![2020-09-03_07 38 33](https://user-images.githubusercontent.com/70701092/92115732-7f13f080-edb8-11ea-9459-b6ba566d7ae3.png)

**Comment by HIPPOKLEIDES** [comment]
Will keep it in mind for the future, but for now this isn't really priority since the block and texture are functional as is
