### ISSUE TITLE
Diagonal spruce wood railing

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#208]
**Is your feature request related to a problem? Please describe.**
Model is inset bit much and it clips the Dark spruce plank step stairs

**Describe the solution you'd like**
To see if it can be adjusted so as not to clipp the stairs

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here.i
I have no way to show video but the edge of the step you would put your foot on is the part that clips

**Comment by Eaglestorm13** [comment]
Ok so i was using these again and noticed it is the Dark spruce plank step stairs seem when facing the stairs as if you were going to walk up them the right side seem it may be bit to offset or long  not sure if the model need shifted or shortend on that side because it does not glitch on that side with the same rails hope that helps

**Comment by HIPPOKLEIDES** [comment]
Can't reproduce or discern an issue
