### ISSUE TITLE
Light limestone cobble wall

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#209]
ConquestReforged-mc1.15.2-4.0.0-v0.72.jar

**Forge Version**    
31.2.36

**Describe the bug**    
Light limestone cobble wall are not connecting as intended i assume.
![2020-09-03_07 43 42](https://user-images.githubusercontent.com/70701092/92116345-53ddd100-edb9-11ea-9637-ad0aa26162d4.png)

**Crash Log**    
If your game crashed please upload a crash log (pastebin.com being the preferred method).

**Screenshots/Video**    
Screen shot added

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**    
I have tried with no CR textures and without shaders and this is for Creative,

**Comment by HIPPOKLEIDES** [comment]
Walls generally workings again
