### ISSUE TITLE
Small wood bench

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#210]
ConquestReforged-mc1.15.2-4.0.0-v0.72.jar

Forge Version
31.2.36

Describe the bug
Small wood bench is connecting to limestone cobble wall
![2020-09-03_07 48 39](https://user-images.githubusercontent.com/70701092/92117043-470dad00-edba-11ea-8711-a25331ba9d73.png)

Crash Log
If your game crashed please upload a crash log (pastebin.com being the preferred method).

Screenshots/Video
Screen shot added

System Information (optional)
Total RAM:
Allocated RAM:
CPU:
GPU:

Additional context
I have tried with no CR textures and without shaders

**Comment by HIPPOKLEIDES** [comment]
Good catch, thanks. Should be fixed in the next alpha release
