### ISSUE TITLE
Glass pane

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#213]
![2020-09-10_08 17 52](https://user-images.githubusercontent.com/70701092/92735586-248e0d80-f33f-11ea-9004-26b1fd10ef71.png)

ConquestReforged-mc1.15.2-4.0.0-v0.8.jar
The specific mod & its version in question.    
You can copy-paste the mod jar's filename here.

**Forge Version**    
31.2.36

**Describe the bug**    
Connecting edge texture seem to be white instead of black or clear however its suppose to be so it blends as it is white now.

**Additional context**

**Comment by ArtemisiaTR** [comment]
Added missing texture to RP
