### ISSUE TITLE
Spruce Wood Trap Doors

### ISSUE THREAD

**Issue by Eaglestorm13** [Conquest-Reforged/Indev#214]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.8.jar

Forge Version
31.2.36

**Forge Version**    
The specific version of Forge you are currently using.

**Describe the bug**    
Missing Textures making parts see thru

**Screenshots/Video**    
![2020-09-11_18 05 18](https://user-images.githubusercontent.com/70701092/92979840-90649900-f459-11ea-917b-04b6d30d8780.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
