### ISSUE TITLE
No connected txt for acacia, birch, jungle step stairs and metal stairs (corners)

### ISSUE THREAD

**Issue by Vitr00x** [Conquest-Reforged/Indev#215]
**Is your feature request related to a problem? Please describe.**
There is no texture for corner pieces for acacia, birch log and jungle step stairs, also metal stairs, as it is for other ones.

**Describe the solution you'd like**
To add a corner texture connected variant as it is in e.g. oak step stairs or spruce

**Describe alternatives you've considered**

**Additional context**
![2020-09-14_22 46 20](https://user-images.githubusercontent.com/71292453/93137043-2c520700-f6dd-11ea-80d9-575f69a646f2.png)

**Comment by HIPPOKLEIDES** [comment]
done
