### ISSUE TITLE
Somehow keep the 1.12 item frame functionality of the shield texture as well as transparency if required 

### ISSUE THREAD

**Issue by Rozsy** [Conquest-Reforged/Indev#216]
**Describe your suggestion**    
Somehow keep the 1.12 item frame functionality of the blue wooden shield texture as well as the new transparency if required 

**Explain why you think your suggestion should be added**    
1.12 gave such a good 2 sided shop sign with the item frame texture, the transparency option gives so many possibilities too would be really good to have an option of either use, maybe even more textures then the blue wooden shield option

**Explain how you think your suggestion can best be implemented**    
Somehow add the option into the block variants (C) menu to pick a shield texture or transparent

**Describe alternatives you've considered**    
Creative Realms mentioned this may have to be its own conquest block model to work

**Additional context**    
I initially thought we had the two options and could not place anything into the blue shield once i had selected it by clicking the frame twice, I later realised i was just placing another item frame IN that initial item frame and conversely seeing the old 1,12 version of the frame and thinking that was its own frame but couldn't place another item (clicking would just rotate the frame as if vanilla) i was very confused for a moment 
![2020-09-23_16 47 05 copy](https://user-images.githubusercontent.com/68055033/94037563-66966500-fdbd-11ea-9d94-1d486c20edcf.png)

**Comment by HIPPOKLEIDES** [comment]
Noted, but unlikely since it doesn't create a very good aesthetic imo
