### ISSUE TITLE
Unlit Hand Candle missing texture/lit candle has no flame

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#217]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-297

**Screenshots/Video**    
<img width="1119" alt="Screenshot_2" src="https://user-images.githubusercontent.com/33978024/95539583-6c17c000-09f7-11eb-9be2-15811a727193.png">

**Comment by HIPPOKLEIDES** [comment]
fxed

**Comment by CreativeRealms** [comment]
Lit candle has transparent faces.
<img width="488" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/95646766-617f2880-0ad4-11eb-987e-04d47c2b4637.png">
