### ISSUE TITLE
limestone_gothic_arch does not sit on block below

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#219]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.8

**Forge Version**    
31.2.36

**Describe the bug**    
The limestone gothic arch does not sit flat on the block below in its single block state as per all the other gothic arches, it does not seem to have been updated the same as the others.

**Crash Log**    
N/A

**Screenshots/Video**    
screenshot added

**System Information (optional)**    
N/A reported by multiple users

**Additional context**    
First noted during Stormbuilds stream
![limestone gothic arch bug](https://user-images.githubusercontent.com/66781812/97757863-9429a900-1af5-11eb-9454-64995ade1364.jpg)
![2020-10-30_21 19 49](https://user-images.githubusercontent.com/66781812/97757906-adcaf080-1af5-11eb-82c1-fd67542785a7.png)

**Comment by HIPPOKLEIDES** [comment]
![2020-10-31_17 04 04](https://user-images.githubusercontent.com/31572523/97789972-00ea8500-1b82-11eb-9d9d-3bf8d7523d91.png)
I've edited this and the sandstone arch to now have an additional brick so the model extends down to the block below
