### ISSUE TITLE
Blue Clay Beaver Tail Tile and Dirty Blue Clay Beaver Tail Tile incorrect variations when pressing C

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#220]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.8

**Forge Version**    
31.2.36

**Describe the bug**    
Both the Blue Clay Beaver Tail Tile and the Dirty Blue Clay Beaver Tail Tile have the incorrect texture/block variations when pressing C on the original solid block (dirty shows clean/clean shows dirty) The textures on slabs/stairs etc etc need to be swapped back over so they show for the correct solid block

**Crash Log**    
N/A

**Screenshots/Video**    
Screenshots added
![dirty - clean blue clay beaver tail tile](https://user-images.githubusercontent.com/66781812/97759157-5c703080-1af8-11eb-83f5-99839635d082.jpg)
![dirty - clean blue clay beaver tail tile2](https://user-images.githubusercontent.com/66781812/97759244-8c1f3880-1af8-11eb-9589-4172d8369693.jpg)

**System Information (optional)**    
N/A reported by multiple users

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed, good catch
