### ISSUE TITLE
Reintroduction of the 1.12.2 support block as its own thing

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#222]
**Is your feature request related to a problem? Please describe.**
Currently, there is no block that covers both the top and side the same way the 1.12 support block does. In 1.15.2 alpha the only way to cover blocks above and to the side (eg on an internal roof) is to use stair blocks which are cumbersome and thick as they cannot be layered.  The new support block does not hide the rear face.

**Describe the solution you'd like**
I would love to see the reintroduction the 1.12 support block which is still highly versatile and fills a need not currently being covered by another existing block shape.
![2020-11-01_18 48 04](https://user-images.githubusercontent.com/66781812/97812188-961b7580-1c77-11eb-8e2c-65fe733a9520.png)

**Describe alternatives you've considered**
Stair blocks are very cumbersome and do not look "refined" in the same way that other 1.15 alpha block shapes do. The newly updated support block model is less versatile.  Having spoken to a lot of the builders on soror who have also built in 1.12 it's pretty unanimous that we'd like to see this block make a comeback if possible.

**Additional context**
the ceiling in 1.12.2 looks much neater and finished
![2020-11-01_18 47 34](https://user-images.githubusercontent.com/66781812/97812209-b3e8da80-1c77-11eb-8435-d24a34609ca8.png)
the ceiling in 1.15.2 looks messier being able to see the roof tile through the support
![2020-11-01_21 21 04](https://user-images.githubusercontent.com/66781812/97818794-6df23d80-1c9c-11eb-949e-07d0ef84f607.png)

**Comment by HIPPOKLEIDES** [comment]
I agree with you that these new support blocks aren't really doing it. I see how the 1.12 can be pretty versatile, but I think this versatility comes at the cost of quality in many situations. As such, I've made something that can be specifically used for supporting things like roofs. I see there being many other types of "support" blocks for stuff like tudor, shelves, etc, but a bit later. 

Let me know if this works alright

Preview around other blocks (full block, vertical slab layer)
![image](https://user-images.githubusercontent.com/31572523/105615605-f534e600-5d9f-11eb-912b-5d2b3be29b5b.png)

Preview of one on its own: 
![image](https://user-images.githubusercontent.com/31572523/105615623-29a8a200-5da0-11eb-9689-78eb4aacc857.png)

**Comment by xElandriax** [comment]
looks very smart, I think its a great alternative to get the same cover of the old support model, looking forward to trying it out

**Comment by HIPPOKLEIDES** [comment]
Added for next alpha release
While this can suffer from the weird shadows you get when placing a full block nearby, you'll be able to avoid them by using the final layer of slabs in the next release that essentially looks the same as a regular full block

**Comment by xElandriax** [comment]
Just a bit of feedback on this new block, it feels a little chunky, and could maybe be slimmed down?  Does it need to expand into the blocks above and below? As the 1.12 version didn't do this and still seemed to connect reasonably well with other blocks or vertical layers/trapdoors etc 

Also can you confirm if there will be corner variations for this as there was for the old 1.12 version to maximise its versatility?
