### ISSUE TITLE
heavy wooden door texture missing on edge

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#223]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9

**Forge Version**    
31.2.45

**Describe the bug**    
When changing the position from open/closed on the heavy wooden door part of the texture on the edge is lost

**Crash Log**    
N/A

**Screenshots/Video**    
![2020-11-01_21 28 08](https://user-images.githubusercontent.com/66781812/97819964-d7c21580-1ca3-11eb-8978-ce8a7bf2d1dd.png)
![2020-11-01_21 28 40](https://user-images.githubusercontent.com/66781812/97819966-da246f80-1ca3-11eb-9c85-5b7bd8abf86c.png)
![2020-11-01_21 30 13](https://user-images.githubusercontent.com/66781812/97819969-dc86c980-1ca3-11eb-8240-5d4b9163152f.png)

**System Information (optional)**    
N/A

**Additional context**    
Confirmed by multiple builders on soror

**Comment by HIPPOKLEIDES** [comment]
fixd
