### ISSUE TITLE
New Candelabrum move slightly when light level increased from 0 - 1

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#226]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9

**Forge Version**    
Forge-31.2.45

**Describe the bug**    
Gold Candelabrum 1
Gold Candelabrum 2
Iron Candelabrum 1
Iron Candelabrum2

All the above move slightly when you increase their light level from 0 to 1  No further movement from 1 - 3, returns to original position from 3 to 0.  Movement is slightly different on both versions.

**Crash Log**    
N/A

**Screenshots/Video**    

![2020-11-22_19 37 13](https://user-images.githubusercontent.com/66781812/99915330-fa6fa900-2cfa-11eb-9888-65e7eef5bcef.png)

**System Information (optional)**    
N/A

**Additional context**    
Candelabrum 3 on both Iron and Gold does not move.

**Comment by HIPPOKLEIDES** [comment]
fixd
