### ISSUE TITLE
New layer blocks have rendering issue with shaders.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#228]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="1039" alt="Screenshot_3" src="https://user-images.githubusercontent.com/33978024/100640400-0a147080-333f-11eb-9726-b33582a7bdb7.png">

**Comment by HIPPOKLEIDES** [comment]
Works fine with a shader pack like shaders. Not our issue to fix
