### ISSUE TITLE
Wrong top CTM limestone gothic window

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#229]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="1362" alt="Screenshot_4" src="https://user-images.githubusercontent.com/33978024/100640600-48aa2b00-333f-11eb-994c-7f5eaed03387.png">

**Comment by HIPPOKLEIDES** [comment]
fixed/duplicate issue
