### ISSUE TITLE
Back side of clothes hangar has borked textures (two states)

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#232]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="464" alt="Screenshot_7" src="https://user-images.githubusercontent.com/33978024/100641362-07fee180-3340-11eb-89be-cb1238e444f7.png">

**Comment by ArtemisiaTR** [comment]
Fixed
