### ISSUE TITLE
Vanilla enchantment table transparency bug

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#233]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="478" alt="Screenshot_8" src="https://user-images.githubusercontent.com/33978024/100642848-fc141f00-3341-11eb-8f42-f0a994a85c25.png">

**Comment by ArtemisiaTR** [comment]
Fixed
