### ISSUE TITLE
Sandstone architrave lighting bug

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#234]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="1072" alt="Screenshot_9" src="https://user-images.githubusercontent.com/33978024/100643140-590fd500-3342-11eb-963e-7c59c9660d41.png">

**Comment by HIPPOKLEIDES** [comment]
not our problem
tweak your graphics settings or don't place full blocks around it
