### ISSUE TITLE
Marble/Sandstone ionian capital lighting bug

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#235]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="1229" alt="Screenshot_11" src="https://user-images.githubusercontent.com/33978024/100643378-a0966100-3342-11eb-9c35-fa0d7501ac54.png">

**Comment by HIPPOKLEIDES** [comment]
not our problem
tweak your graphics settings or don't place full blocks around it
