### ISSUE TITLE
Loom shading bug

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#236]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="433" alt="Screenshot_13" src="https://user-images.githubusercontent.com/33978024/100643544-e0f5df00-3342-11eb-9d1b-942ef8ef66f6.png">

**Comment by HIPPOKLEIDES** [comment]
not our problem
tweak your graphics settings or don't place full blocks around it
