### ISSUE TITLE
Lantern bad pixel

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#238]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="371" alt="Screenshot_16" src="https://user-images.githubusercontent.com/33978024/100644004-6bd6d980-3343-11eb-9147-66c15ab5009c.png">

**Comment by ArtemisiaTR** [comment]
Fixed
