### ISSUE TITLE
New model for canelbalara (weird Y bit on top)

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#239]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-310

**Screenshots/Video**    
<img width="704" alt="Screenshot_17" src="https://user-images.githubusercontent.com/33978024/100644175-a5a7e000-3343-11eb-84c7-d57fdbf2a359.png">

**Comment by ArtemisiaTR** [comment]
Tweaked model a bit. Might be done a proper model later.
