### ISSUE TITLE
Make cabinets/workbenches not have random textures?

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#242]
**Describe your suggestion**    
ConquestReforged-mc1.15.2-4.0.0-310

<img width="728" alt="Screenshot_19" src="https://user-images.githubusercontent.com/33978024/100646803-316f3b80-3347-11eb-8495-22c497376fbf.png">

**Comment by HIPPOKLEIDES** [comment]
ok separated them into 4 blocks
