### ISSUE TITLE
Large Metal Pot texture error when placed below another block

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#247]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9

**Forge Version**    
forge 31.2.45

**Describe the bug**    
when the conquest:large_metal_pot is placed below another block of any type it looses some of its side textures
see screenshots

**Crash Log**    
N/A

**Screenshots/Video**    
![2020-11-19_02 06 36](https://user-images.githubusercontent.com/66781812/103419340-8bebf980-4b8a-11eb-8ffd-d8d958bfd69a.png)
![2020-11-19_02 07 19](https://user-images.githubusercontent.com/66781812/103419343-8ee6ea00-4b8a-11eb-861b-c5a82bfda1eb.png)
![2020-11-19_02 07 40](https://user-images.githubusercontent.com/66781812/103419350-927a7100-4b8a-11eb-83a8-7adcea94ed92.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixd
