### ISSUE TITLE
Clothes hanger corner does not appear in decor tab

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#248]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9

**Forge Version**    
forge 31.2.45

**Describe the bug**    
the conquest:clothes_hanger_corner does not appear in the decor tab with the straight version

**Crash Log**    
N/A

**Screenshots/Video**    
![2020-12-31_17 08 54](https://user-images.githubusercontent.com/66781812/103419485-3106d200-4b8b-11eb-9ec2-35f9d266b6b7.png)
![2020-12-31_17 09 09](https://user-images.githubusercontent.com/66781812/103419489-349a5900-4b8b-11eb-8cea-ace4eb2b96e6.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by CreativeRealms** [comment]
Did you try using the C menu?

**Comment by xElandriax** [comment]
Yes, however when we pointed this out during one of filthys streams you said to do a GitHub report. :)  There's so much inconsistency between things appearing and not appearing and using the C menu or the debug stick it becomes a nightmare for any new player coming into to use the mod.  Does it cause load or coding issues for variations to show in the tabs? None of us knew it was even an item to be used until Jane randomly found it and showed the rest of us.

**Comment by CreativeRealms** [comment]
Individual blocks are supposed to show up in tabs and variants of those blocks in the C menu. Blockstates are a separate thing which uses the debug stick.
