### ISSUE TITLE
conquest:diagonal_spruce_beam_railing and many other beams do not appear in any tab unless searched for

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#249]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9

**Forge Version**    
forge 31.2.45

**Describe the bug**    
conquest:diagonal_spruce_beam_railing does not appear in planks and beams or advanced carpentry, nor do many other the beam types

**Crash Log**    
N/A

**Screenshots/Video**    
![2020-12-31_17 13 33](https://user-images.githubusercontent.com/66781812/103419672-da4dc800-4b8b-11eb-8b35-319f688e910a.png)

**System Information (optional)**    
N/A

**Additional context**    
Are there any other colour types of this same block planned?

**Comment by HIPPOKLEIDES** [comment]
It can be found in the block palette of "horizontal_spruce_wood_railing". It's the same for many other beams, which are found in the block palette of whichever beam is in the creative tab and has the same texture
