### ISSUE TITLE
Make curtain hitbox thicker

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#25]
![2020-02-04_07 01 42](https://user-images.githubusercontent.com/33978024/73715310-3f026780-471c-11ea-95f9-26ac975d9c7a.png)

**Comment by HIPPOKLEIDES** [comment]
If this were a quick fix, I'd jump on it, but this requires a lot of bloat for a small one pixel extension of a hit-box. 
Can't see this changing in the foreseeable future. So, will close this

**Comment by CreativeRealms** [comment]
Reopening because clarification of THICKER not longer. :P

**Comment by HIPPOKLEIDES** [comment]
Thinking about this again, not so hot on it still. It'll create an inconsistency among pane blocks. Not only is that a bunch of vanilla blocks to overwrite, but also a lot of classes to bloat for something small
