### ISSUE TITLE
conquest:chains_on_the_ground no options to change chain type from curled to straight

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#250]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.9

**Forge Version**    
forge 31.2.45

**Describe the bug**    
when placing chain to create upward diagonal lengths they default frequently to the curled version with no debug option to select the straight texture.

**Crash Log**    
N/A

**Screenshots/Video**    
![2020-12-31_20 22 59](https://user-images.githubusercontent.com/66781812/103424852-9916e180-4ba6-11eb-8332-74b96afdba78.png)

**System Information (optional)**    
N/A
**Additional context**

**Comment by HIPPOKLEIDES** [comment]
I've fixed this for the "ascending" shape blockstates, which should now only use the straight texture. This was controlled by CTM and happened when there was no block for the rail to connect to (optifine doesn't check diagonally for this). This functionality is still there for the north_south and east_west blockstates though
