### ISSUE TITLE
conquest:cross_beams missing textures

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#256]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10

**Forge Version**    
forge 31.2.45

**Describe the bug**    
Missing textures on some faces when in use 

**Crash Log**    
N/A

**Screenshots/Video**    

![2021-01-08_00 44 12](https://user-images.githubusercontent.com/66781812/104850094-ee602c00-58e4-11eb-8cfc-51bf050a526b.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
good catch, should be fixed in the next mod alpha release
