### ISSUE TITLE
conquest:rough_palm_board_fence corner section missing textures when in use

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#257]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10

**Forge Version**    
forge 31.2.45

**Describe the bug**    
missing textures on faces for the corner version of the rough palm board fence

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-12_00 10 22](https://user-images.githubusercontent.com/66781812/104850150-544cb380-58e5-11eb-9539-656b79795553.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed in the next alpha mod release
