### ISSUE TITLE
pink / purple carpet in wrong GUI purple carpet overriden

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#259]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10.1
AND
ConquestReforged-mc1.15.2-4.0.0-v0.10

**Forge Version**    
forge 31.2.45

**Describe the bug**    
The pink carpet displays in the GUI for purple carpet - no purple carpet available

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-24_23 06 00](https://user-images.githubusercontent.com/66781812/105646721-60161800-5e99-11eb-9078-decaf2de00fc.png)
![2021-01-24_23 07 09](https://user-images.githubusercontent.com/66781812/105646724-63a99f00-5e99-11eb-83ef-f72fd09e1950.png)
![2021-01-24_23 07 18](https://user-images.githubusercontent.com/66781812/105646731-67d5bc80-5e99-11eb-84d9-bfaf0e78a2be.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed in the next release
