### ISSUE TITLE
Cloth tab is missing vanilla carpets

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#26]

**Comment by HIPPOKLEIDES** [comment]
Vanilla carpets are in the variant wheel families of the full block carpets (same texture, looks a little better in the creative tabs)

**Comment by CreativeRealms** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/33978024/73784187-ac0a1180-479d-11ea-8482-314eff7c0746.png)
So why are these ones in there?

**Comment by HIPPOKLEIDES** [comment]
Haven't received carpet textures for those four blocks.
