### ISSUE TITLE
conquest ovens cause lag spikes

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#260]
**Mod Version & Build Number**    
all to date - reported by Filthy on Soror server

**Forge Version**    
31.2.45

**Describe the bug**    
both the conquest oven blocks have been causing lag spikes when used on Soror.  May need to contact Filthy_Coin to get server logs?

**Crash Log**    
N/A

**Screenshots/Video**    

![2021-01-26_23 04 09](https://user-images.githubusercontent.com/66781812/105924775-ea47b300-6036-11eb-8316-318bb732c2b0.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
These furnaces essentially use the same code as vanilla furnaces (ie: they extend the vanilla block class without overriding anything). Vanilla furnaces in the past have been notorious for creating lag to the point that they're used grief/shutdown servers. Do vanilla furnaces create a similar issue?

**Comment by xElandriax** [comment]
Filthy has given me the following screenshot for you, this is from soror
![image](https://user-images.githubusercontent.com/66781812/106384665-f2e81280-63c3-11eb-9a9c-9af230c4de2f.png)

this is the error the furnaces throw
every time chunk loads in and whenever it is interacted with placed or broken

hope that helps?

**Comment by HIPPOKLEIDES** [comment]
Alright, these errors should be gone with the next release. Not sure how it'll impact performance, but I guess it helps a bit to not have those spamming the console

**Comment by HIPPOKLEIDES** [comment]
assuming the lag has been mitigated/fixed
