### ISSUE TITLE
Tarred Spruce Wood beam pillar - wrong texture

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#261]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10.1

**Forge Version**    
31.2.45

**Describe the bug**    
incorrect texture on the pillar - reported by Choriphus on Soror

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-26_23 00 25](https://user-images.githubusercontent.com/66781812/105924994-427eb500-6037-11eb-90d9-f84d51c1c542.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
![2021-01-29_11 02 02](https://user-images.githubusercontent.com/31572523/106298094-74536f80-6221-11eb-8aef-0e9b4a0532e3.png)

I checked the files as well and they use the same texture. This seems more like an issue of color perception with the smaller pillar seeming like a different shade when isolated from a slightly larger pillar that has the vertical dark lines on its sides
