### ISSUE TITLE
Tarred Spruce Wood beam wall - wrong texture - does not connect

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#262]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10.1

**Forge Version**    
31.2.45

**Describe the bug**    
wall does not connect, has incorrect texture - reported by Choriphus on Soror

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-26_22 52 59](https://user-images.githubusercontent.com/66781812/105925114-807bd900-6037-11eb-8741-65662f592ded.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed the wall connections for all the tarred wood beams. the texture color is not only caused by illusions of color perception but also smooth lighting (the full block beam darkens the block next to it)
