### ISSUE TITLE
White Painted Wooden Railing Fence - clips texture of texture beneath if placed on a 1/4 pillar/fence piece

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#263]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10.1

**Forge Version**    
31.2.45

**Describe the bug**    
clips texture of texture beneath if placed on a 1/4 pillar/fence piece - reported by Choriphus on Soror

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-26_22 51 36](https://user-images.githubusercontent.com/66781812/105925230-ab662d00-6037-11eb-8683-eb12fbbaa157.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed
