### ISSUE TITLE
new gothic window versions weird CTM shenanigans

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#264]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10.1

**Forge Version**    
31.2.45

**Describe the bug**    
CTM for the new gothic window/glass is not working as intended - compared to the original gothic window glass
Affected glass - 
light_limestone_gothic_window
sandstone_gothic_window
tan_sandstone_gothic_window

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-26_22 40 06](https://user-images.githubusercontent.com/66781812/105925559-48c16100-6038-11eb-9964-750d88174578.png)
![2021-01-26_22 40 00](https://user-images.githubusercontent.com/66781812/105925563-4b23bb00-6038-11eb-9292-0ba1fc9b16b9.png)
![2021-01-26_22 39 52](https://user-images.githubusercontent.com/66781812/105925568-4ced7e80-6038-11eb-833b-c7ee00992a99.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed via resourcepack update now
