### ISSUE TITLE
carved oak wood pillar has no bottom texture on several layers

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#265]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10.1

**Forge Version**    
31.2.45

**Describe the bug**    
the pillar for some of the layers does not have any base texture

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-26_22 25 20](https://user-images.githubusercontent.com/66781812/105925892-cf763e00-6038-11eb-9bc6-c276cb97eb56.png)
![2021-01-26_22 24 55](https://user-images.githubusercontent.com/66781812/105925897-d1d89800-6038-11eb-9d3c-4fbbc1791abd.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
was an issue with the sphere/egg hitboxes being larger than the actual model in some places
the hitboxes are more accurate/complex and this should now be fixed
