### ISSUE TITLE
Improvements to config setting for visual block variations

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#266]
**Describe your suggestion**    
Secret config setting for block variations - to make this more versatile and user-friendly, is it possible to include a 0 option to revert the block back to being able to layer normally rather than fixed - which is what we have when this is not set to true (0-7 with no visual representations)

**Explain why you think your suggestion should be added**    
Rather than having to keep this as SPR SKRIT mod users could have a fully implemented visual guide to what layer version of the block they are placing, rather than having to guess by scrolling though existing 0-7 

**Explain how you think your suggestion can best be implemented**    
The addition of the "0" unchanged block layer to the list so it can be layered up as normal without having to reselect the block to "reset" it 

**Describe alternatives you've considered**    
The alternative is to have the existing 0-7 with no visual representations.  No biggie, but not as user friendly

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
The main reason this is still in the "secret" config is that another dev who is no longer with us wrote the code and I'm uncertain as to whether its worth maintaining+improving. Will have to see in the future
