### ISSUE TITLE
Inclusion of a variety of wooden round and gothic arches

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#267]
**Is your feature request related to a problem? Please describe.**
Currently, we have no form of the improved wooden arch sets - they would be exceedingly useful both in medieval and modern builds

**Describe the solution you'd like**
The addition of some basic wood type arches, eg the "foundation" woods such as oak/birch/spruce in both the round and gothic arch types.

**Describe alternatives you've considered**
Currently, the only alternative is to use existing block slabs and stairs to try and create arches as we did in 1.12

**Additional context**
![2021-01-26_23 05 16](https://user-images.githubusercontent.com/66781812/105926646-511a9b80-603a-11eb-8a44-bf6c1c723d32.png)

Timber-framed buildings need smooth arches, please!

**Comment by HIPPOKLEIDES** [comment]
It's not a bad idea, and the foundations have been laid for decorative wooden arches in the future. For the scenario you've shown in the picture though, the branch blocks have been put to good use by some builders lately
