### ISSUE TITLE
Simple Elven Column Design  - does not have directional support

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#269]
**Is your feature request related to a problem? Please describe.**
Simple Elven Column Design  - does not have directional support - The "top" design makes great accenting for architecture reported by Choriphus

**Describe the solution you'd like**
The ability to have stacked or the "single" top texture that is already on the block.  IE to be able to rotate it or select the visual face when using for detailing or building.

**Describe alternatives you've considered**
no alternatives for being able to use this texture in walls etc.

**Additional context**
great on floors, not accessible for walls

![2021-01-26_23 03 28](https://user-images.githubusercontent.com/66781812/105927413-d94d7080-603b-11eb-8532-b117cb9b7d7d.png)

**Comment by HIPPOKLEIDES** [comment]
done and ready for next release
