### ISSUE TITLE
Redstone torch has default textures

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#27]
![2020-02-04_07 31 55](https://user-images.githubusercontent.com/33978024/73748504-451b3700-4762-11ea-8839-ec1bd77d4eed.png)

**Comment by HIPPOKLEIDES** [comment]
Need mechanical texture/model as discussed a while ago
No reason to make this another candle that has less functionality than the candles we already have

**Comment by CreativeRealms** [comment]
Monster says he sent it on the git.

**Comment by HIPPOKLEIDES** [comment]
Fixed in latest version of RP / fixed in build 63+
