### ISSUE TITLE
yellow travertine decor pillar - does not have directional support

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#270]
**Is your feature request related to a problem? Please describe.**
yellow travertine decor pillar  - does not have directional support - The "top" design makes great accenting for architecture 

**Describe the solution you'd like**
The ability to have stacked or the "single" top texture that is already on the block.  IE to be able to rotate it or select the visual face when using for detailing or building.

**Describe alternatives you've considered**
no alternatives for being able to use this texture in walls etc. when using more than 1 of it 

**Additional context**
great on floors or single blocks, not accessible for walls or pillar variations

![2021-01-26_23 02 31](https://user-images.githubusercontent.com/66781812/105927556-23365680-603c-11eb-9d8d-e24846780db9.png)

example provided by filthy_coin for best solution (and colour alternatives ;) )
![image](https://user-images.githubusercontent.com/66781812/105927632-4cef7d80-603c-11eb-9649-43fea070a033.png)

**Comment by HIPPOKLEIDES** [comment]
it is now directional/stackable for the next release
