### ISSUE TITLE
carved wood (advanced carpentry tab) blocks need stair models adding if not extra shape variations for detailing

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#272]
**Is your feature request related to a problem? Please describe.**
WHYyyyyy is it that the most decorative blocks, used specifically in most cases for detailing builds do not have even the most basic shapes EG stair blocks?  Exceedingly frustrating because they have so much potential that is wasted by not having a greater variety of shapes.

**Describe the solution you'd like**
Include block shape variations such as stairs, lintels, modern 1.15 type blocks for detailing and versatility

**Describe alternatives you've considered**
The only alternative is to not use the blocks for detailing and then that means they are a waste of resources and textures.

**Additional context**
![2021-01-26_22 31 51](https://user-images.githubusercontent.com/66781812/105928683-f420e480-603d-11eb-8c55-71be8ad6bc86.png)
![2021-01-26_22 32 23](https://user-images.githubusercontent.com/66781812/105928689-f6833e80-603d-11eb-8579-2ba891c0c54b.png)

**Comment by HIPPOKLEIDES** [comment]
will work on getting more basic shapes for these in before full release

**Comment by HIPPOKLEIDES** [comment]
Was under the impression that most of these had stair variants in 1.12 for some reason. In any case, I already have it on my list for the future to add stairs/slabs for a number of similar blocks.
