### ISSUE TITLE
New skinny arch models is it possible to turn them upside down? (EG full circle effect)

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#273]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to rotate the new arch styles so they can be used upside down

**Describe the solution you'd like**
Do not know if this would require whole new blocks for the upside down versions, almost like being able to hinge them vertically not horizontally like we do with some of the other models

**Describe alternatives you've considered**
no upside-down alternatives apart from small corner block models

**Additional context**

![2021-01-26_22 38 08](https://user-images.githubusercontent.com/66781812/105928914-64c80100-603e-11eb-87fd-9e7d8321b3f4.png)

**Comment by HIPPOKLEIDES** [comment]
It'd be a lot more models to make for edge use cases, and these were made primarily for arches created to reinforce walls
