### ISSUE TITLE
Improvements to many of the old plant models/textures

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#274]
**Is your feature request related to a problem? Please describe.**
It would be lovely to see many of the existing plant models and blocks being upgraded to 1.15 styling for more floof like the lovely new leaf blocks.

**Describe the solution you'd like**
EG white clematis would look amazing if it were styled like the new leaf blocks

**Describe alternatives you've considered**

**Additional context**
Would also be nice to see more floofy dangly plants.  Old vines don't really cut it

![2021-01-26_22 29 20](https://user-images.githubusercontent.com/66781812/105929995-ae195000-6040-11eb-830e-f53961dccf9c.png)

**Comment by CreativeRealms** [comment]
Plant textures are going to be reworked so this will likely be fixed eventually.
