### ISSUE TITLE
Addition of mossy versions of graywacke mortar wall and slate light mortar wall

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#276]
**Is your feature request related to a problem? Please describe.**
would be great to have mossy versions of both of these rustic block textures

**Describe the solution you'd like**
mossy block versions of both

**Describe alternatives you've considered**
other mossy blocks do not blend

**Additional context**
![2021-01-26_12 37 23](https://user-images.githubusercontent.com/66781812/105932179-6bf20d80-6044-11eb-9750-fec7b1f3ba69.png)
![2021-01-26_12 38 13](https://user-images.githubusercontent.com/66781812/105932184-6dbbd100-6044-11eb-9dbe-30addd3ad691.png)

**Comment by HIPPOKLEIDES** [comment]
Asked Monster about this a while back and he wasn't particularly enthusiastic about creating additional mossy variants.
