### ISSUE TITLE
Dark oak plank block does not have a vertical corner slab variation

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#277]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.10

**Forge Version**    
31.2.45

**Describe the bug**    
no half slab vertical corner on this model exists reported by Choriphus on soror

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-01-27_01 28 58](https://user-images.githubusercontent.com/66781812/105932344-a9ef3180-6044-11eb-90aa-3db69e1ae297.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
All of the vanilla planks should have that variant now in the next alpha
