### ISSUE TITLE
Rustic_fence does not connect to itself internal corner

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#280]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
forge 31.2.47

**Describe the bug**    
when trying to place this particular fence in a diagonal line the blocks do not connect, they seem to be inverted 

**Crash Log**    
N/A

**Screenshots/Video**    

![2021-02-04_10 33 22](https://user-images.githubusercontent.com/66781812/107124088-968c6380-6899-11eb-9cf3-1dc87cb23ca6.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
right click the fence and it'll toggle which side the horizontal planks are on
