### ISSUE TITLE
Jungle_Fence_Gate texture or clipping errors

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#281]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
forge 31.2.47

**Describe the bug**    
texture or clipping errors

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-02-04_10 43 54](https://user-images.githubusercontent.com/66781812/107124135-dc492c00-6899-11eb-9c26-7171b64f5112.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed in latest alpha rp
