### ISSUE TITLE
many updated layers are not displaying consistently in the GUI

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#282]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
forge 31.2.47

**Describe the bug**    
many of the updated/renamed layer versions are inconsistent sizes in the GUI - examples given below

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-02-04_11 33 22](https://user-images.githubusercontent.com/66781812/107124299-fd5e4c80-689a-11eb-9511-c3fdc271e726.png)
![2021-02-04_11 33 30](https://user-images.githubusercontent.com/66781812/107124301-ffc0a680-689a-11eb-90e4-ed94cec4b54c.png)
![2021-02-04_11 33 34](https://user-images.githubusercontent.com/66781812/107124302-018a6a00-689b-11eb-91da-76f4c89d9042.png)
![2021-02-04_11 33 44](https://user-images.githubusercontent.com/66781812/107124305-08b17800-689b-11eb-8aa4-09472d5db5d4.png)
![2021-02-04_11 33 51](https://user-images.githubusercontent.com/66781812/107124307-0c44ff00-689b-11eb-9e86-66eaa7a09040.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
wouldnt say this is a bug. the different sizes indicate different functionality (small layer shape only has layers, slab shape has layers and top/bottom states)
