### ISSUE TITLE
birch_wood_railing_small_pillar clipping 

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#283]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
forge 31.2.47

**Describe the bug**    
clipping issues for the block below

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-02-04_13 01 13](https://user-images.githubusercontent.com/66781812/107124356-5ded8980-689b-11eb-9036-63e8f1daed8e.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed next alpha mod build
