### ISSUE TITLE
Loose Cobble Wall - Wrong Texture

### ISSUE THREAD

**Issue by TimTGodfrey** [Conquest-Reforged/Indev#284]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11
ConquestReforgedRP-ALPHA-83

**Forge Version**    
forge-1.15.2-31.2.47

**Describe the bug**    
Limestone Cobble Wall appears in both the picker and in-game with the Loose Limestone Cobble texture

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-02-08_14 20 01](https://user-images.githubusercontent.com/17678678/107282627-26c1d880-6a53-11eb-9647-8f031ad5cc42.png)
![2021-02-08_21 15 53](https://user-images.githubusercontent.com/17678678/107282674-36412180-6a53-11eb-87fc-c3f4c799d0aa.png)
![2021-02-08_21 15 12](https://user-images.githubusercontent.com/17678678/107282681-393c1200-6a53-11eb-818e-e149724f93e3.png)

**System Information (optional)**    
Total RAM: 
Allocated RAM:    
CPU:    
GPU:

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
got this one fixed. thanks!
