### ISSUE TITLE
capital layers cause consistent bug when layered up to full block size - see crash log

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#285]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
31.2.45

**Describe the bug**    
When going from "Layer 3" to "layer 4" - full block using vertical layers the client crashes out 

**Crash Log**    
[crash-2021-02-18_22.57.29-client.txt](https://github.com/Conquest-Reforged/Indev/files/6012508/crash-2021-02-18_22.57.29-client.txt)

https://pastebin.com/Us3JRXrd

**Screenshots/Video**    

![2021-02-19_19 38 17](https://user-images.githubusercontent.com/66781812/108553038-09f69200-72ea-11eb-8093-fdf70b75f09b.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed for next alpha
