### ISSUE TITLE
Birch Fence Gate does not attach to fences and resets fence blocks when debugged and opened/closed

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#286]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
31.2.45

**Describe the bug**    
Birch Fence Gate will not attach to thin white picket fence.  When the side fences are debugged to attach, they are reset when they register a block update through the opening and closing of the gate

**Crash Log**    
N/A

**Screenshots/Video**    

![2021-02-19_19 42 35](https://user-images.githubusercontent.com/66781812/108553701-fb5caa80-72ea-11eb-8351-be21544c65a3.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should connect in next release (as a side effect will also connect with fences)
