### ISSUE TITLE
multiple waterlogged item blocks have default water texture

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#287]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
31.2.45

**Describe the bug**    
When waterlogged the following decoration item blocks display default water textures - wicker basket, cauldron with grille, large metal pot, empty barrel - unlike the main cauldron which shows shader water.

**Crash Log**    
N/A

**Screenshots/Video**    

First screenshot taken with SEUS 
![2021-02-19_19 50 00](https://user-images.githubusercontent.com/66781812/108554208-b127f900-72eb-11eb-9661-2d879d3c5235.png) 
Second screenshot taken with internal shaders
![2021-02-19_19 52 39](https://user-images.githubusercontent.com/66781812/108554531-1e3b8e80-72ec-11eb-863c-f1220815f5e8.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
Should be fixed now. The vanilla cauldron didnt have water tinting on it, whereas the others did. Looks a lot better now!
