### ISSUE TITLE
cartography tables no connected textures

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#288]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
31.2.45

**Describe the bug**    
Not sure if this is intended or not. It would be nice for the cartography table to have a connected map same way the map layer block does

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-02-19_20 02 02](https://user-images.githubusercontent.com/66781812/108558511-ea636780-72f1-11eb-879e-a1a95ba94232.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by ArtemisiaTR** [comment]
Fixed.
