### ISSUE TITLE
First Style Red Stucco Panel in 2 tabs

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#289]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
31.2.45

**Describe the bug**    
First Style Red Stucco Panel block appears both in advanced masonry and in plaster stucco and paint tabs

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-02-19_21 49 08](https://user-images.githubusercontent.com/66781812/108566444-56e46380-72fe-11eb-88a3-ee9326486213.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fxed
