### ISSUE TITLE
Add leaded or detailed "glass" into the gothic/tracery windows (also possible bug)

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#290]
**Is your feature request related to a problem? Please describe.**
There seems to be some slightly strange behaviour going on with the gothic window blocks, that they will not display glass behind them. I was trying to add leaded glass detailing to the gothic tracery windows by doing a layer of more detailed glass behind, but it does not show at all though the first glass pane.  I have no idea if this is unexpected behaviour or not??

**Describe the solution you'd like**
Can we have diamond lead or similar added to the gothic tracery windows so the block looks like there is actual glass in it rather than completely clear?  Anything similar to the other existing diamond glass panes would look great.

**Describe alternatives you've considered**
Adding a second layer of glass behind is not possible as it disappears when viewed through the first pane of glass

**Additional context**
![2021-02-20_11 23 13](https://user-images.githubusercontent.com/66781812/108593988-1113b380-736f-11eb-88ed-646d80e74384.png)
![2021-02-20_11 24 42](https://user-images.githubusercontent.com/66781812/108593989-140ea400-736f-11eb-91e6-d467ec408c39.png)

**Comment by HIPPOKLEIDES** [comment]
While it's expected behavior for glass blocks to cull faces from other glass blocks, I've made it so these tracery windows dont cull faces from other glass blocks.
