### ISSUE TITLE
conquest:wooden_roof_supports lighting bug

### ISSUE THREAD

**Issue by HFranzALT** [Conquest-Reforged/Indev#291]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.11

**Forge Version**    
1.15.2-forge-31.2.48

**Describe the bug**    
A lighting bug on the block conquest:wooden_roof_supports while facing:west.

**Crash Log**    
n/a

**Screenshots/Video**    

![2021-03-01_16 50 00](https://user-images.githubusercontent.com/60790360/109530223-64dc7600-7aae-11eb-9035-8e0a042a825c.png)
![2021-03-01_16 50 36](https://user-images.githubusercontent.com/60790360/109530240-67d76680-7aae-11eb-939a-0107cfe3811d.png)
![2021-03-01_16 50 43](https://user-images.githubusercontent.com/60790360/109530253-69a12a00-7aae-11eb-903c-936aef40946d.png)

**System Information (optional)**    
Total RAM: 32GB
Allocated RAM:  16GB  
CPU: i7 7700k   
GPU: Nvidia GTX 1070 

**Additional context**    
Can sometimes occur on the facing:south blockstate, but very faintly.

**Comment by CreativeRealms** [comment]
Try turning your smooth lighting setting to 0-5%. Most shading issues are Optifine bugs and out of our control.

**Comment by HFranzALT** [comment]
> Try turning your smooth lighting setting to 0-5%. Most shading issues are Optifine bugs and out of our control.

Adjusted both Smooth Lighting Level and Dynamic lights both together and sperately, no change.

**Comment by CreativeRealms** [comment]
I did some tests and it seems to fix it when you have shaders on and smooth lighting at 0%. Without shaders changing settings has no effect (and I couldn't recreate the really dark shadows like you have in your pic).

**Comment by HFranzALT** [comment]
Which shaders are you using?

**Comment by HFranzALT** [comment]
Is there a fix for without using shaders? Would be good to find a fix that doesn't rely on shaders.

**Comment by HIPPOKLEIDES** [comment]
You can turn off the "Old Lighting" option and it'll get rid of the weird shadows

![image](https://user-images.githubusercontent.com/31572523/110840031-3d399a80-8272-11eb-8112-246dd449c554.png)
![2021-03-11_14 01 39](https://user-images.githubusercontent.com/31572523/110840108-55111e80-8272-11eb-9f14-16d90528af48.png)

**Comment by HFranzALT** [comment]
Can confirm this did fix it, ideal.
