### ISSUE TITLE
Centered horizontal and vertical wooden beams

### ISSUE THREAD

**Issue by HFranzALT** [Conquest-Reforged/Indev#292]
**Is your feature request related to a problem? Please describe.**
Frustrated when needing to create certain details such as watermills, mechanisms etc where centered horizontal and vertical wooden beams would be ideal.

**Describe the solution you'd like**
Centered horizontal and vertical wooden beams. Just two new beam variants, one being centered within a block vertically and the other horizontally.

**Describe alternatives you've considered**
Using log beams can sometimes be used for the vertical, but not horizontal, often doesn't look right or fit.

**Additional context**
n/a

**Comment by HIPPOKLEIDES** [comment]
it has been done
