### ISSUE TITLE
Colored variants of Clouds and/or Glass(without any Patterns)

### ISSUE THREAD

**Issue by Moonrocks420** [Conquest-Reforged/Indev#293]
**Is your feature request related to a problem? Please describe.**

- In Vanilla MC I enjoyed layering different types of glass to create a colored fog effect, but since the colored glass has very specific textures which make it quite hard working something out.

**Describe the solution you'd like**

- Probably for this issue specifically adding colored variants of either Clouds or Glass Blocks (+panes). Of which the latter likely would find a use as flames. Edit: while on the Topic of Recolors I believe recolored versions for Water especially with 1.13s Waterlogging system could work quite well.

**Describe alternatives you've considered**

- Unfortunately, I didn`t have the pleasure to test 1.15.2 myself yet, but of the given Palette in 1.12 I didn't manage to find any combination to achieve the wanted effect.

**Additional context**
![maxresdefault](https://user-images.githubusercontent.com/52468380/109991351-8b96e880-7d0a-11eb-8477-1bd07279e832.jpg)

**Comment by CreativeRealms** [comment]
Plain colored glass will 100% not be a thing because it would look like a default/vanilla block and not fit the theme of the mod. Recolored clouds are unlikely but I will leave it up to the other devs to decide since it at least falls within the Conquest texture theme.

**Comment by HIPPOKLEIDES** [comment]
There are some water biome color variations. Will add some flatter glass for modern builds, but not for the purpose of fog
