### ISSUE TITLE
Block request

### ISSUE THREAD

**Issue by KatskoDarwin** [Conquest-Reforged/Indev#294]
Can we get some short of cannon block? Maybe the make another variation of the artillery quarter slab centered or something,

**Comment by CommanderAJ021** [comment]
Thank you for your work, it is truly incredible! Is it possible to get more yellow stucco variations and blocks that mesh really well with [it?] As well as an older looking sand stone brick similar to [this]?
Stucco (https://st3.depositphotos.com/16349414/18676/i/1600/depositphotos_186765298-stock-photo-old-worn-sandstone-wall.jpg)
Brick (https://i2.wp.com/www.rabbieitan.com/wp-content/uploads/2017/05/jerusalem-israel-1065007_1280.jpg?fit=915%2C686&ssl=1)?

**Comment by CreativeRealms** [comment]
We no longer take asset requests on the GitHub. You can post them on the Discord if you want.
