### ISSUE TITLE
Broken transparency - Various blocks

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#3]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the bug**    
The following blocks have broken transparency:    
- [x] Oak wood table transparency
- [x] Stage floor transparency
- [x] Blue and green buntings
- [x] Yellow and red buntings
- [x] Clothes line
- [x] Straight saw
- [x] Dried tobacco
- [x] Sausages on hooks
- [x] Pig on a spit
- [x] Grass covered limestone

**Comment by dags-** [comment]
Probably missing our `@Render` annotation on their Block class

**Comment by HIPPOKLEIDES** [comment]
The classes for all of these have the appropriate @Render annotations now. Some of these have the acacia texture issue, which is separate.
