### ISSUE TITLE
Door edge texture bug (happens with most doors)

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#303]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-346

**Screenshots/Video**    
<img width="204" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/110591264-865df180-8181-11eb-826d-e81f9697cdba.png">

**Comment by HIPPOKLEIDES** [comment]
Not really a bug, just doesn't have a texture specifically for the sides
