### ISSUE TITLE
Inconsistent shutter opening mechanic

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#304]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-346

**Screenshots/Video**    
<img width="315" alt="Screenshot_2" src="https://user-images.githubusercontent.com/33978024/110591356-a55c8380-8181-11eb-9c5e-3d11e0379935.png">

**Comment by HIPPOKLEIDES** [comment]
dun
