### ISSUE TITLE
Potentially edit trellis texture to be more consistent with other variants.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#305]
<img width="677" alt="Screenshot_3" src="https://user-images.githubusercontent.com/33978024/110591478-cae98d00-8181-11eb-9fd4-e2bba8ab7054.png">

**Comment by HIPPOKLEIDES** [comment]
![2021-03-28_14 18 02](https://user-images.githubusercontent.com/31572523/112762959-6d9e6a00-8fd0-11eb-950c-e7d2a3d1f970.png)
