### ISSUE TITLE
borked CTM on conquest:orange_plaster_with_sndstone_base

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#307]
**Mod Version & Build Number**    
V11

**Forge Version**    
31.2.49

**Describe the bug**    
connected textures do very strange things with this block. Inconsistent "features" show up in large walls

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-03-10_19 00 47](https://user-images.githubusercontent.com/66781812/110683052-88e93700-81d3-11eb-9e86-2d7d3861c4a3.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed
