### ISSUE TITLE
A basic shrub block, similiar to the Hawthorn just without bushes.

### ISSUE THREAD

**Issue by HFranzALT** [Conquest-Reforged/Indev#308]
**Is your feature request related to a problem? Please describe.**
I often struggle with creating scertain foliage as a lot of the bushes look good, but have berries. You can set tick speed to 0 but this isn't really the best fox for those that don't want to do this.

**Describe the solution you'd like**
A basic shrub block, similiar to the Hawthorn just without bushes perhaps.

**Describe alternatives you've considered**
Setting random tick speed to 0, but not really the best for all players.

**Additional context**
n/a

**Comment by CreativeRealms** [comment]
Done
