### ISSUE TITLE
Pallet texture issues

### ISSUE THREAD

**Issue by dandelionmom** [Conquest-Reforged/Indev#309]
Conquest Reforged 3.0.2 (using the CR launcher)

**Forge Version**    
14.23.5.2847

**Describe the bug**    
When placing a full block on top of a wood pallet, the edges of the pallet go invisible on the top side, but are fine underneath.  Happens on at least the driftwood and mossy driftwood pallets. Only full blocks seem to be causing the problem.

**Crash Log**    
NA

**Screenshots/Video**    
![2021-03-11_13 31 56](https://user-images.githubusercontent.com/64164481/110843815-550f1f80-826e-11eb-94a5-a80d27c60852.png)
![2021-03-11_13 32 17](https://user-images.githubusercontent.com/64164481/110843820-56d8e300-826e-11eb-94f8-4ac9df00ba70.png)

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**

**Comment by CreativeRealms** [comment]
Didn't know this was a 1.12.2 bug. Since 1.12.2 isn't being updated anymore I'm closing this issue.
