### ISSUE TITLE
Chests have weird shadow on top and get replaced with default textures when doubled

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#31]
![2020-02-04_07 21 39](https://user-images.githubusercontent.com/33978024/73749026-35502280-4763-11ea-9d5a-40f3f9ec3baf.png)
![2020-02-04_07 21 41](https://user-images.githubusercontent.com/33978024/73749027-35e8b900-4763-11ea-8904-901b0cee5388.png)
![2020-02-04_07 21 48](https://user-images.githubusercontent.com/33978024/73749028-35e8b900-4763-11ea-9545-5c5a16ee036a.png)

**Comment by HIPPOKLEIDES** [comment]
Chest uv-mapping completely changed in 1.15.2

**Comment by HIPPOKLEIDES** [comment]
fixed build 88+
