### ISSUE TITLE
Red shutter has broken opening mechanic.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#312]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-359

**Screenshots/Video**    
<img width="437" alt="Screenshot_7" src="https://user-images.githubusercontent.com/33978024/111767023-e30e8a00-88ae-11eb-87fe-4f140df14c4e.png">

**Comment by HIPPOKLEIDES** [comment]
fixd
