### ISSUE TITLE
Vertical lime mortar orange clay brick texture isn't seamless.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#315]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-359

**Screenshots/Video**    
<img width="421" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/111862857-ad29de00-8960-11eb-9932-0173d52a71d6.png">

**Comment by HIPPOKLEIDES** [comment]
made repeat instead of random
