### ISSUE TITLE
Corner clothes hanger model size.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#318]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-396

**Screenshots/Video**    
<img width="351" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/113478334-e4d07400-9490-11eb-88d5-41cfe9bd862c.png">
<img width="1061" alt="Screenshot_3" src="https://user-images.githubusercontent.com/33978024/113478335-e7cb6480-9490-11eb-8aca-9de6060ab465.png">
<img width="384" alt="Screenshot_2" src="https://user-images.githubusercontent.com/33978024/113478339-ec901880-9490-11eb-96f7-b213b5d83f2d.png">

**Comment by ArtemisiaTR** [comment]
Fixed
