### ISSUE TITLE
Texture clipping on oak_wood_table

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#320]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.13

**Forge Version**    
31.2.50

**Describe the bug**    
Table is being clipped by itself

**Crash Log**    
N/A

**Screenshots/Video**    

![2021-04-06_17 27 11](https://user-images.githubusercontent.com/66781812/114205933-b9e39580-9952-11eb-94df-ef96d603eda3.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed
