### ISSUE TITLE
texture clipping on fancy_wooden desk/yellow_carpet

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#321]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.13

**Forge Version**    
31.2.50

**Describe the bug**    
fancy wooden desk being clipped by carpet blocks

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-04-08_23 00 39](https://user-images.githubusercontent.com/66781812/114206596-6887d600-9953-11eb-95ca-9eaafc811bc3.png)
![2021-04-08_23 00 44](https://user-images.githubusercontent.com/66781812/114206603-6b82c680-9953-11eb-96ee-09ab336bb516.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed
