### ISSUE TITLE
z-fighting on side of wooden towel rail

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#322]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.13

**Forge Version**    
ConquestReforged-mc1.15.2-4.0.0-v0.13

**Describe the bug**    
left side bracing of wooden towel rail (as you look at the front) has an issue with the curved bracket section - needs to be moved to prevent the z-fighting that makes it flicker.

**Crash Log**    
N/A

**Screenshots/Video**    
![2021-04-09_16 50 28](https://user-images.githubusercontent.com/66781812/114210488-be5e7d00-9957-11eb-8771-3121d3baa8cb.png)
![2021-04-09_16 50 36](https://user-images.githubusercontent.com/66781812/114210510-c3233100-9957-11eb-9893-2d3e87a6ecb8.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
fixed

**Comment by xElandriax** [comment]
> fixed

z-fighting is now even worse in v13.1 both the sides and the back are now having the issue.
![2021-04-17_16 08 58](https://user-images.githubusercontent.com/66781812/115117660-9eead400-9f97-11eb-954c-f941d71acd61.png)
![2021-04-17_16 09 11](https://user-images.githubusercontent.com/66781812/115117662-a01c0100-9f97-11eb-92b7-a0e85f882cd2.png)
