### ISSUE TITLE
Basic bookcase, make "lit lantern" texture a separate block

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#323]
**Is your feature request related to a problem? Please describe.**
The lit lantern inside the bookcase shows up way too repetitively.
![2021-04-09_16 40 21](https://user-images.githubusercontent.com/66781812/114213045-6b39f980-995a-11eb-8748-42a922c70241.png)

**Describe the solution you'd like**
Make a separate block for the lantern texture and leave the bookcase as just the book selections. This will give the builder the ability to add the lit lanterns where they actually look right.

**Describe alternatives you've considered**

**Additional context**

**Comment by CreativeRealms** [comment]
It won't be a separate block but it will show up less often now.
