### ISSUE TITLE
Spruce chair sideways placement

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#33]
![2020-02-04_07 09 16](https://user-images.githubusercontent.com/33978024/73749176-819b6280-4763-11ea-9801-2f95c2914bd3.png)

**Comment by CreativeRealms** [comment]
Chair places sideways rather than facing forwards like all other chairs.

**Comment by HIPPOKLEIDES** [comment]
Fixed in build 61+
