### ISSUE TITLE
Resizeable Eighth Slabs

### ISSUE THREAD

**Issue by ricey125** [Conquest-Reforged/Indev#331]
**Describe your suggestion**    
Give eighth slabs the same function of size change that regular slabs and quarter slabs have

**Explain why you think your suggestion should be added**    
This can allow a smoother connection between two horizontal quarter slabs, making a corner

**Explain how you think your suggestion can best be implemented**    
Use the same method on how slabs are resized, I believe through different blockstates if Im not mistaken?

**Describe alternatives you've considered**    
Cant really try alternatives.

**Additional context**    
https://imgur.com/a/VARLU9j

**Comment by HIPPOKLEIDES** [comment]
Have considered this in the past, but I don't think the amount of models is worth the potential cost to load and store all of the additional necessary models at launch.
