### ISSUE TITLE
UV/Lighting Bug Clavicytherium 

### ISSUE THREAD

**Issue by Hearthseeker** [Conquest-Reforged/Indev#333]
ConquestReforged-mc1.15.2-4.0.0-v0.14
Forge: 1.15.2-31.2.0

Lighting bug, East-West Facing Clavicytherium has additional shading on top of the model whereas North-South facing has additional shading on the side of the model   
![2021-05-03_13 06 02](https://user-images.githubusercontent.com/64628155/116908069-7823d300-ac10-11eb-9195-2d8bdabf56c8.png)

**Comment by Hearthseeker** [comment]
Panel shading difference still slightly noticeable with smooth lighting set to off
![2021-05-03_13 51 27](https://user-images.githubusercontent.com/64628155/116912848-bfad5d80-ac16-11eb-8f41-7860f0be5e8a.png)

**Comment by HIPPOKLEIDES** [comment]
Put a non-full block under it (ie: slab) and it'll go away
