### ISSUE TITLE
Crash With Layered Red Clay Tiles

### ISSUE THREAD

**Issue by Argent2** [Conquest-Reforged/Indev#336]
**ConquestReforged-mc1.15.2-4.0.0-v0.14**    

**1.15.2**    

**CTD when placing Red Clay Tiles Slab/Light Red Clay Tiles Slab's 5th block state (full block)**    

**https://pastebin.com/8eP5mqF6**       

**Haven't tested other roof blocks**

**System Information (optional)**    
Total RAM: 32gb   
Allocated RAM:   24gb 
CPU:    i7 8700k
GPU:    GTX 1080

**Comment by HIPPOKLEIDES** [comment]
Should be fixed in the next release
