### ISSUE TITLE
Wooden gothic windows don't have glass break sound.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#341]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-493

**Comment by HIPPOKLEIDES** [comment]
![unknown](https://user-images.githubusercontent.com/31572523/120648825-1098b780-c44a-11eb-8389-5f9e2c23e8fc.png)

probably because they are wood and don't have any glass
