### ISSUE TITLE
HIGH PRIORITY Tall rose bush, tall grass block both cause immediate game crash on placement

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#342]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.15

**Forge Version**    
31.2.50

**Describe the bug**    
On placement of any "tall" / 2 high plant, it causes an immediate game crash to the launcher. Trying to place other blocks next to these plants also causes immediate game crash. 

**Crash Log**    
[crash-2021-06-03_14.50.11-client.txt](https://github.com/Conquest-Reforged/Indev/files/6592215/crash-2021-06-03_14.50.11-client.txt)
[crash-2021-06-03_14.55.35-client.txt](https://github.com/Conquest-Reforged/Indev/files/6592216/crash-2021-06-03_14.55.35-client.txt)
[crash-2021-06-03_15.05.06-client.txt](https://github.com/Conquest-Reforged/Indev/files/6592217/crash-2021-06-03_15.05.06-client.txt)

**Screenshots/Video**    
none available due to crash

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
Should be fixed with latest update
