### ISSUE TITLE
Flax plant reverted to old model?

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/Indev#344]
**Mod Version & Build Number**    
V15.1

**Forge Version**    
31.2.50

**Describe the bug**    
Flax plants previously (in V14.1) were "full" like the current tall grass plants (2 block high model) they have defaulted to an older? I think - I could be incorrect - model which is only an X shape, so in fields, it now looks very very uniform and not particularly "natural" the way other crops/plants do when they are planted in large areas.

**Crash Log**    
N/A

**Screenshots/Video**    
![flax plant old model](https://user-images.githubusercontent.com/66781812/120905351-58396200-c649-11eb-9ca5-b2a68f0fc41e.jpg)
![flax plant old model2](https://user-images.githubusercontent.com/66781812/120905352-5a9bbc00-c649-11eb-9625-19d8c0c0ba16.jpg)
![tallgrassmodel](https://user-images.githubusercontent.com/66781812/120905363-71daa980-c649-11eb-87fa-b1be2b719548.jpg)

**System Information (optional)**    
N/A

**Additional context**    
Not sure this is actually a bug, or a model that's been altered on purpose or unintentionally. However, the more bushy/fuller version looks much more natural. It would be great if it could be updated or added in as an alternative plant?

**Comment by xElandriax** [comment]
Creative has mentioned maybe the offset is broken?  Asked to add to the report :)

**Comment by HIPPOKLEIDES** [comment]
![2021-06-08_17 38 07](https://user-images.githubusercontent.com/31572523/121261149-54435500-c880-11eb-9591-64ebd671c20f.png)
fixed
