### ISSUE TITLE
Arabian arched window pane 

### ISSUE THREAD

**Issue by eag-inc** [Conquest-Reforged/Indev#346]
ConquestReforged-mc1.15.2-4.0.0-v0.15

1.15.2-forge-31.2.0

'Arabian arched window pane' has a wrong (old texture) lower face when used inside a small arch

![2021-06-06_18 44 29](https://user-images.githubusercontent.com/83931490/120915363-4adab100-c6f7-11eb-897a-6bd256ded06a.png)

**Comment by HIPPOKLEIDES** [comment]
Fixed
