### ISSUE TITLE
Wheels bug

### ISSUE THREAD

**Issue by WhiteWindXX** [Conquest-Reforged/Indev#348]
![2021-06-12_00 12 44](https://user-images.githubusercontent.com/66167634/121717030-57a23f00-cb13-11eb-8706-dc2457887c13.png)

**Comment by CreativeRealms** [comment]
We need more details on how to recreate this since it does not happen on our end. It might be a shader issue so try disabling yours and see if it still happens.

**Comment by WhiteWindXX** [comment]
> We need more details on how to recreate this since it does not happen on our end. It might be a shader issue so try disabling yours and see if it still happens.

Shader issue indeed, closed
