### ISSUE TITLE
Gothic window panes not connecting properly to the arch.

### ISSUE THREAD

**Issue by Aequipondium** [Conquest-Reforged/Indev#349]
**Mod Version & Build Number**    
1.15.2

**Forge Version**    
forge 1.15.2-31.2.49

**Describe the bug**    
When placing the gothic window panes under an arch, the textures don't connect.

**Crash Log**    
N/A

**Screenshots/Video**   

**System Information (optional)**    
Total RAM:   32GB RAM 
Allocated RAM:    10GB RAM
CPU:    AMD Ryzen 9 3900x
GPU: RTX 2080 super

**Additional context**    
N/A
![2021-06-12_00 00 41](https://user-images.githubusercontent.com/55962315/121753042-c7172f00-cb11-11eb-8e16-9de317f1d630.png)

**Comment by Aequipondium** [comment]
Also with the launcher version the arches don't appear when i have shaders activated.
![2021-06-12_00 25 45](https://user-images.githubusercontent.com/55962315/121754464-fe3b0f80-cb14-11eb-9b48-a7b87bc9c252.png)

**Comment by Monsterfisch** [comment]
the arches showing up as errors is a shader issue specifically and the window not connecting cannot be avoided at the moment

**Comment by Aequipondium** [comment]
To clarify, the first picture was with hrfranz's video instructions. As you can see, shaders work fine with the arches. However in the launcher version it does not.
