### ISSUE TITLE
no world generation

### ISSUE THREAD

**Issue by petrus-legend** [Conquest-Reforged/Indev#351]
**Mod Version & Build Number**    
The specific mod & its version in question.    
You can copy-paste the mod jar's filename here. conquestreforged-mc1.15.2-4.0.0-498

**Forge Version**    
The specific version of Forge you are currently using.   1.15.2-forge-31.2.0

**Describe the bug**    
A clear and concise description of what the bug is.    It seems that when i generate a new world in the 1.15.2 mod, it just generates a vanilla world with conquest textures. it looks nothing like the 1.12.2 generator.

**Crash Log**    
If your game crashed please upload a crash log (pastebin.com being the preferred method).

**Screenshots/Video**    
Provide screenshots or video to aid your bug description.  
If the issue relates to a block, please screenshot it with the `F3` debug menu open and your crosshair over the block you're reporting (this allows us to see exactly what blockstate is affected).

**System Information (optional)**    
Total RAM:    64g
Allocated RAM:    8g
CPU:    intel i9
GPU: nvidia rtx geforce2080s

**Additional context**    
Add any other context about the problem here.n
![2021-06-13_13 00 22](https://user-images.githubusercontent.com/61907578/121804581-5d00a600-cc47-11eb-951f-9f1c444ba1c2.png)

**Comment by HIPPOKLEIDES** [comment]
Not a bug, that world generation wasn't ported. Use the Terraforged mod for better terrain.
