### ISSUE TITLE
A chunk of my build disappeared after a lighting bug and a game crash.

### ISSUE THREAD

**Issue by SirAxart** [Conquest-Reforged/Indev#352]
**Mod Version & Build Number**
ConquestReforged v4.0.0-498

**Forge Version**    
Forge v31.2.50

**Describe the bug**
A chunk of my build disappeared after I placed a block which apparently caused the entire build to be affected by a lighting bug and the game to crash.

**Crash Log**    
https://pastebin.com/HamFGqR4

**Screenshots/Video**    
https://prnt.sc/15diejp

**System Information (optional)**    
Total RAM: 16 GB
Allocated RAM: min 8 GB; max 10 GB
CPU: AMD Ryzen 9 3900X 12-Core
GPU: NVIDIA GeForce RTX 3070

**Additional context**    
I was placing scroll rack vertical slabs. The first ones were fine but then I placed one which destroyed the block it was put on (grass block iirc) and the whole build was affected by a lighting bug. The game crashed soon after (after me not doing anything, only placing and destroying blocks, trying to see if the lighting bug would go away). When I started the game up again and joined the world, the entire chunk it happened in was missing.

**Comment by HIPPOKLEIDES** [comment]
I would get rid of journeymap. It seems to be rife with issues, causing things like this... 
![image0](https://user-images.githubusercontent.com/31572523/121890225-1911ad80-cce8-11eb-9a09-13028f7b3031.png)

Otherwise it could be Optifine and one of it's settings. It's unlikely to be our mod because we don't change the lighting system

**Comment by SirAxart** [comment]
I'm running it from the official 1.15.2 profile in the launcher and I never changed any OptiFine settings. Don't know where the problem is, that's why I posted a bug report. Maybe the crashreport will tell, but that's for someone else to tell me, as I can't make heads or tails of it.

**Comment by HIPPOKLEIDES** [comment]
Have tried to recreate this, but to no avail, with or without journeymap. From what I understand, the crash-log says that the game tried to use a light-value beyond the acceptable range of light-values. It references lines from Minecraft itself, Forge, and Optifine (making this situation more difficult given that it is completely closed source). 

In any case, I recommend trying to play without Journeymap. Also do not turn on antialiasing and anistropic filtering (broken Optifine features). Some users have turned these on for some reason while using the launcher and experienced game-breaking issues. If it happens again, do share a post with any relevant details

**Comment by HIPPOKLEIDES** [comment]
stale issue
