### ISSUE TITLE
Dependency menu appears even when Optifine/resourcepack are installed and enabled.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#354]
**Mod Version & Build Number**    
conquest-4.0.0-498

**Screenshots/Video**    
<img width="639" alt="Screenshot_1" src="https://user-images.githubusercontent.com/33978024/121996359-1d55cd80-cdb1-11eb-9b50-9bbd85c492ad.png">

**Comment by HIPPOKLEIDES** [comment]
Seems to be fixed
