### ISSUE TITLE
Birch log vertical corner slab 

### ISSUE THREAD

**Issue by ghost** [Conquest-Reforged/Indev#359]
ConquestReforged-mc1.15.2-4.0.0-v0.15.2

1.15.2-forge-31.2.0

Incorrect block face when the 'wall of birch logs vertical corner slab' is placed upside-down 2 blocks wide

![2021-06-21_00 17 09](https://user-images.githubusercontent.com/83931490/122673866-b1e38400-d226-11eb-8d0a-35993e091399.png)

**Comment by HIPPOKLEIDES** [comment]
should be fixed for next release
