### ISSUE TITLE
"Big Ladder" texture bug

### ISSUE THREAD

**Issue by SirAxart** [Conquest-Reforged/Indev#360]
**Mod Version & Build Number**
ConquestReforged v4.0.0-498

**Forge Version**
Forge v31.2.50

**Describe the bug**
Upon placing a block (almost any model/variant, apparently) in front of a Big Ladder, its texture gets fucked up.

**Crash Log**

**Screenshots/Video**
https://prnt.sc/16qucni
https://prnt.sc/16qw1t6

**System Information (optional)**
Total RAM: 16 GB
Allocated RAM: min 8 GB; max 10 GB
CPU: AMD Ryzen 9 3900X 12-Core
GPU: NVIDIA GeForce RTX 3070

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
should be fixed for next release
