### ISSUE TITLE
[1.15.2-4.0.0] Grass "overflow" overlay missing

### ISSUE THREAD

**Issue by TheBrambleShark** [Conquest-Reforged/Indev#362]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-498

**Forge Version**    
1.15.2 HD U G6

**Describe the bug**    
When a grass block and some other blocks are adjacent, a grass texture is applied to the edge of the cobble block to simulate grass "overflowing" onto the cobble. This shows as a semi-transparent green tile instead.

Sometimes, looking at the texture at the right angle (usually when applied to vertical surfaces) will render the overlay correctly.

**Crash Log**    
N/A

**Screenshots/Video** 
Grass adjacent to cobble:
![2021-06-25_11 08 25](https://user-images.githubusercontent.com/7003081/123454104-b665bf00-d5cf-11eb-84d8-f29ed049b352.png)

Grass next to stone brick (vertical surface):
![2021-06-25_11 09 48](https://user-images.githubusercontent.com/7003081/123454282-e90fb780-d5cf-11eb-8b5d-9c235dbdc152.png)
![2021-06-25_11 09 51](https://user-images.githubusercontent.com/7003081/123454288-ea40e480-d5cf-11eb-9e4b-c7b3094263a2.png)

**System Information (optional)**    
Total RAM: 64gb
Allocated RAM: 6gb
CPU: Intel I9-9900K
GPU: NVidia GeForce RTX 2070 Super

**Additional context**    
Horizontal surfaces do not appear to be affected by viewing angle in the same way as vertical surfaces. For vertical surfaces, the viewing angle must be very shallow (almost directly above or below) in order for the texture to render properly.

**Comment by HIPPOKLEIDES** [comment]
do you have antialiasing or anistropic filtering enabled?

**Comment by TheBrambleShark** [comment]
I have anisotropic filtering enabled at level 16 and antialiasing off currently.

**Comment by HIPPOKLEIDES** [comment]
make sure those are all off. they're broken optifine features

**Comment by TheBrambleShark** [comment]
After turning both off, I can confirm that the issue has been resolved.

It also resolved a transparent water issue I had felt would be related since both were affected by viewing angle.
