### ISSUE TITLE
[1.15.2 4.0.0] Hole between farmland and dirt path

### ISSUE THREAD

**Issue by TheBrambleShark** [Conquest-Reforged/Indev#363]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-498

**Forge Version**    
1.15.2-forge-31.2.50

**Describe the bug**    
When a dirt path block is adjacent to a farmland block, a gap is visible which allows you to see under the farmland block.

**Screenshots/Video**    
![2021-06-25_16 10 02](https://user-images.githubusercontent.com/7003081/123485650-0a859900-d5fa-11eb-98a3-23e69db706a6.png)

**Additional context**
This works for planted and unplanted farmland and the type of crop does not affect it.

**Comment by HIPPOKLEIDES** [comment]
vanilla farmland model lowered back to vanilla height to avoid this
