### ISSUE TITLE
Empty Small Old Wicker Basked wrong break particles

### ISSUE THREAD

**Issue by Moredir** [Conquest-Reforged/Indev#365]
Mod Version 4.0.0-498

Description:
Break particles are blue

![2021-07-01_10 32 23](https://user-images.githubusercontent.com/85825065/124093212-ed1c5900-da57-11eb-9276-0fadf67210e5.png)
![2021-07-01_10 32 26](https://user-images.githubusercontent.com/85825065/124093225-f0afe000-da57-11eb-87f7-1546b22c7fb3.png)

**Comment by HIPPOKLEIDES** [comment]
should be fixed for next release
