### ISSUE TITLE
Seethrough Bug for Cobblestone Stairs and wrong texture for worn light gray pflaster

### ISSUE THREAD

**Issue by aNetflixOriginal** [Conquest-Reforged/Indev#366]
**Mod Version & Build Number**    
ConquestReforged-mc1.16.5-5.0.0

**Forge Version**    
1.16.5-forge-36.1.32

**Describe the bug**    
The Cobblestone Stairs block is seetrough and got a oak ladder texture on it.

**Crash Log**    
If your game crashed please upload a crash log (pastebin.com being the preferred method).

**Screenshots/Video**    
![2021-07-13_04 05 44](https://user-images.githubusercontent.com/87348990/125382480-05647000-e396-11eb-8b0d-b4bc532b5a3f.png)
![2021-07-13_04 42 25](https://user-images.githubusercontent.com/87348990/125382577-2fb62d80-e396-11eb-965f-ba3af83ad63b.png)
![2021-07-13_04 42 27](https://user-images.githubusercontent.com/87348990/125382582-317ff100-e396-11eb-8695-c1b4c0cdea00.png)
Provide screenshots or video to aid your bug description.  
If the issue relates to a block, please screenshot it with the `F3` debug menu open and your crosshair over the block you're reporting (this allows us to see exactly what blockstate is affected).

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
Second and third pictures show that the Conquest Reforged resourcepack isn't being used, and that the Conquest_ resourcepack is instead being used (incompatible with the mod) without connected textures being turned on.

First picture, the Conquest Reforged resourcepack again doesn't seem to be used given the lack of connected textures on the dirty cobble. Can't recreate oak ladder textures on cobblestone stairs with proper installation. Could potentially be remedied with a restart of the game or reloading textures (press f3+t) if problem persists
