### ISSUE TITLE
Paintings GUI isn't working

### ISSUE THREAD

**Issue by Amoksa** [Conquest-Reforged/Indev#368]
Conquest reforged 1.15.2-4.0.0-498

**Forge Version**    
1.15.2-forge-31.2.45

**Describe the bug**    
Paintings GUI isn't working. I can get it open with "V" but cannot move between paintings. Arrow keys worked in 1.12.2 but do nothing now. I'm using a laptop so now scroll available.

**Comment by HIPPOKLEIDES** [comment]
added this back for next release. thanks
