### ISSUE TITLE
Man Finds 4 TEXTURE Related Issues, He Lives To Regret It | Dhar Mann

### ISSUE THREAD

**Issue by Moonrocks420** [Conquest-Reforged/Indev#369]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-498

**Forge Version**    
31.2.49

**Describe the bug**    
1. The wheel of "Railed Hand Cart is not fully connecting in some places. (All the States are affected by it)
2. Spawn Eggs are missing from the Creative Inventory. (proposal to rename from Spawn Egg to Spawn Scroll to match its texture)
3. Ores lack dynamic textures (especially noticeable for Emerald and Diamond). Not exactly sure if Optifine supports this.
4. Anvil & Beacon GUI both still have a Ring above the Inventory which was Intended to "hold" the Nameplate which is missing entirely. That same ring is abcent in the Horses GUI. This is just something that you cannot Un-see once you notice it.

**Screenshots/Video**    
Issue 1
![Cart1](https://user-images.githubusercontent.com/52468380/126579591-a6675d63-6ea5-4755-9cea-a21a3f79be12.png)
![Cart2](https://user-images.githubusercontent.com/52468380/126579600-4d4956a2-e4ef-4bfc-b065-fd4b299f7113.png)
Issue 3
![Ores](https://user-images.githubusercontent.com/52468380/126579622-3aa7c35b-5a6f-49de-bba2-f80828371a95.png)
Issue 4
![anvil](https://user-images.githubusercontent.com/52468380/126579726-695e1026-1551-4643-af5a-43910d302d17.png)

**Comment by HIPPOKLEIDES** [comment]
1) This should be fixed for the next release. Thanks
2) I think it's easier to just search for the appropriate egg since there are so many eggs and the texture doesn't indicate what mob each one is very well.
3) Optifine doesn't automatically make the overlay work between every block
4) Not really bothered by this
