### ISSUE TITLE
Hawthorn bush doesn't vary with layer

### ISSUE THREAD

**Issue by yixxxxxxxx** [Conquest-Reforged/Indev#370]
**Mod Version & Build Number**    
com.conquestreforged:conquest:4.0.0-498

**Forge Version**    
31.2.50

**Describe the bug**    
When hawthorn bush is placed above a layered block, it does not sink down to match the height of the layer, despite layer being a block state for hawthorn when toggled with the debug stick. The model also does not change height when the layer block state is editted using the debug stick. 

**Screenshots/Video**    
Provide screenshots or video to aid your bug description.  
If the issue relates to a block, please screenshot it with the `F3` debug menu open and your crosshair over the block you're reporting (this allows us to see exactly what blockstate is affected).

https://user-images.githubusercontent.com/88602008/130085658-6becc3ee-f253-4b23-8bb9-c6d00621e685.mp4

**Comment by HIPPOKLEIDES** [comment]
not intended for the model right now
