### ISSUE TITLE
Metal stairs bug

### ISSUE THREAD

**Issue by Kidney-02** [Conquest-Reforged/Indev#371]
**Mod Version & Build Number**    
1.15.2

**Forge Version**    
31.2.50

**Describe the bug**    
metal stairs moved by a bit when turned

**Screenshots/Video**    
![Base Profile Screenshot 2021 09 12 - 14 13 33 85](https://user-images.githubusercontent.com/84661204/132987613-8377d97f-e2cb-4045-898a-83b521214698.png)
![Base Profile Screenshot 2021 09 12 - 14 14 09 65](https://user-images.githubusercontent.com/84661204/132987615-b9304e80-5ae7-42e3-9a1d-8ce450e66a67.png)
![Base Profile Screenshot 2021 09 12 - 14 18 58 62](https://user-images.githubusercontent.com/84661204/132987618-2539dc7a-0907-4450-a782-88e62c84cafc.png)

**System Information (optional)**    
Total RAM:    32
Allocated RAM:   8 - 14 
CPU:  i7-8750H
GPU: gtx1060

**Comment by HIPPOKLEIDES** [comment]
fixed for next release
