### ISSUE TITLE
Architrave models.

### ISSUE THREAD

**Issue by GuanYu1993** [Conquest-Reforged/Indev#372]
**Mod Version & Build Number**    
Conquest Reforged 1.15 full release.
4.0.0

**Forge Version**    
31.2.50

**Describe the bug**    
All of the 3/4th wide architrave block corner models are bugged.

**Screenshots/Video**    
https://i.imgur.com/lW2f30J.png
https://i.imgur.com/jGDg7pX.png
https://i.imgur.com/pQA8Paa.png
https://i.imgur.com/9keqtii.png
https://i.imgur.com/HQvPDlw.png

**System Information (optional)**    
Total RAM:    32GB
Allocated RAM:    Min 12GB Max 16GB
CPU:    AMD Ryzen 9 5900X 12-Core 3.70 GHz
GPU:    INNO3D GEFORCE RTX 3080Ti

**Additional context**    
Tested it on the server and in single player.

**Comment by HIPPOKLEIDES** [comment]
Should be fixed for next release. Thanks for the report!
