### ISSUE TITLE
1.16.5 - Vanilla Lantern not correctly mapped 

### ISSUE THREAD

**Issue by MadAlbinW** [Conquest-Reforged/Indev#373]
**Mod Version & Build Number**    
ConquestReforged-mc1.16.5-5.0.2

**Forge Version**    
Forge 36.2.8

**Describe the bug**    
(Vanilla) lantern/wall lantern not correctly mapped when placed in new 1.16 positions/variations

**Screenshots/Video**    
https://imgur.com/a/XXMWxK9

**System Information (optional)**    
Total RAM: 64gb
Allocated RAM: 16gb
CPU:  AMD Ryzen 9 5900X
GPU: Nvidia gtx1070

**Additional context**    
Adding conquest reforged (mod) causes the texture to be incorrectly mapped in certain situations. Tested with and without resource pack. The mod seems to be what's what's causing it. noticed a day after that torches do the samething when placed on the upper half of a full block.

**Comment by HIPPOKLEIDES** [comment]
Tested vanilla lantern and torch. They work fine for me.
The block in your picture isn't actually a vanilla block, it's a block added by the "torchslabmod". If that mod can't handle lanterns or torches with custom models, that'd be something for them to look into.
