### ISSUE TITLE
Cactus In A Pot Has Default Texture

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#374]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.1.1 (likely also occurs on 1.16)

**Screenshots/Video**    
![image](https://user-images.githubusercontent.com/33978024/146788555-fa984cf0-1685-4b16-be3e-3cd6ce002bab.png)

**Comment by HIPPOKLEIDES** [comment]
fixed in 1.16
