### ISSUE TITLE
textures missing in CR 1.16.5 Alpha

### ISSUE THREAD

**Issue by KEFarris** [Conquest-Reforged/Indev#375]
**Mod Version & Build Number**    
1.16.5 Alpha from download on 1/5/22

The following blocks have the wrong textures (after world conversion from CR 1.15.2)
dark oak trap door - is a blue color slab
oak trap door - is a colored slab
oak door - has the top and bottom of two different doors
Black stone (all three versions - selection menu is correct, but all three are some other generic block when used
laundry barrel is now a Cyan Shulker Box
grass and tall grass are missing textures.

Was this the correct place to report this?

**Comment by CreativeRealms** [comment]
When you say "convert" do you mean you opened it in 1.16.5 or you used the converter and then opened it in 1.16.5?

**Comment by KEFarris** [comment]
I just opened it in 1.16.5  CR  It was previously built in 1.15.2 CR.

**Comment by CreativeRealms** [comment]
Can you post pictures of what is happening in the world as well as the resourcepack selection screen?

**Comment by KEFarris** [comment]
Yes.  I will need to wait until I am back home in about 9 hours.

**Comment by KEFarris** [comment]
![resource selection scrren](https://user-images.githubusercontent.com/60556538/148465605-442bbacf-8b4c-45f0-ba3e-18a482a23010.png)
![Mod Screen](https://user-images.githubusercontent.com/60556538/148465612-bfa6a981-306b-4daf-9207-4d0654751c1e.png)
![Blackstone (all versions)](https://user-images.githubusercontent.com/60556538/148465626-1e388159-36d3-4ec4-b21f-cd90cccb5304.png)
![Dark Oak Trapdoor](https://user-images.githubusercontent.com/60556538/148465631-195ac4e1-4d5c-415a-95f6-ba384f05b14e.png)
![Grass (and tall grass)](https://user-images.githubusercontent.com/60556538/148465637-210099d0-640e-46b6-b6ef-6278f9ce176a.png)
![Laundry Barrel](https://user-images.githubusercontent.com/60556538/148465641-84f5acaf-5eff-42c5-86cd-ab5097e800f9.png)
![Oak Door](https://user-images.githubusercontent.com/60556538/148465665-72cf3af2-72d5-4fa6-b9d1-a304ebb9944d.png)
![Oak Trap Door](https://user-images.githubusercontent.com/60556538/148465670-13b4c4e1-96e9-4e27-9fca-6c7b0b757479.png)
![Other Oak Door](https://user-images.githubusercontent.com/60556538/148465681-c41589b1-d264-405f-abf0-74a3da8f09c9.png)

**Comment by HIPPOKLEIDES** [comment]
Mod Resources should go above Default in the resource pack screen

**Comment by KEFarris** [comment]
Thanks.  That fixed it!
