### ISSUE TITLE
Torch with Grille has a collision box, unlike regular torch

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#376]
**Mod Version & Build Number**    
ConquestReforged-mc1.18.2-7.0.1

**Forge Version**    
40.1.21

**Describe the bug**    
Adding a `conquest:torch_wtih_grille` in a narrow staircase led me to find it had a hitbox, unlike the regular torch that doesnt impede passage.

**Crash Log**    
(none)

**Screenshots/Video**    
![2022-06-01_00 05 32](https://user-images.githubusercontent.com/36215122/171326100-7df5359a-d48c-4bbc-a88d-f1999543e435.png)

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**    
Playing 1.18.2 in Survival with the 1.16 ConquestRecipes datapack to be able to create most blocks in that mode ( i doubt it affects anything, but I'm letting you know)

**Comment by HIPPOKLEIDES** [comment]
changed this to not have a collision box for next update
