### ISSUE TITLE
Some pig has weird textures...

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#378]
**Mod Version & Build Number**    
ConquestReforged-mc1.18.2-7.0.1

**Forge Version**    
40.1.21

**Describe the bug**    
Some pigs have blurry textures in 1.18.2... Not all tho. Some render normally (like previous versions of CR i played) and others are white/yellow/grey.

**Crash Log**    
(none)

**Screenshots/Video**    
![2022-05-30_16 54 04](https://user-images.githubusercontent.com/36215122/171328570-554e60e5-a026-4340-a03f-13009428ab46.png)

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**    
(none)

**Comment by CreativeRealms** [comment]
Animal textures are largely fixed on our end. We are just cleaning up some more bugs before releasing them in an update.
