### ISSUE TITLE
Huge Mushroom under texture seems flipped 

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/Indev#379]
**Mod Version & Build Number**    
Mod: ConquestReforged-mc1.18.2-7.0.2
Resource Pack: CRRP-1.18.2-7.0.3

**Forge Version**    
40.1.21

**Describe the bug**    
Texture beneath the Huge Mushroom don't seem to align/connect properly

**Crash Log**
(none)

**Screenshots/Video**    
![2022-06-04_23 09 36](https://user-images.githubusercontent.com/36215122/172033584-bf02e13e-19d5-45ba-98e0-202725766aa7.png)

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**    
-

**Comment by HIPPOKLEIDES** [comment]
fixed
