### ISSUE TITLE
Broken colormap - Various blocks

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#4]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the bug**    
The following blocks have broken colormapping: 
- [x] Lianas
- [x] Moss vines
- [x] Thick ivy

**Comment by dags-** [comment]
Broken = no color mapping at all or the wrong color mapping?

**Comment by CreativeRealms** [comment]
> Broken = no color mapping at all or the wrong color mapping?

None at all. Vines are white.

**Comment by HIPPOKLEIDES** [comment]
All these should have the appropriate props for colors and their items fixed
