### ISSUE TITLE
Realms + accessibility settings GUI textures

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#47]
![2020-02-04_17 18 48](https://user-images.githubusercontent.com/33978024/73758460-4dc83900-4773-11ea-9555-09e09afe68f7.png)
![2020-02-04_17 18 51](https://user-images.githubusercontent.com/33978024/73758520-60db0900-4773-11ea-8dff-e786bd005446.png)

**Comment by dags-** [comment]
Think phil has added these to the resourcepack

**Comment by CreativeRealms** [comment]
It's not fully finished. There is still the weird vanilla diamond thing (which makes the text hard to read) 
![Screenshot_1](https://user-images.githubusercontent.com/33978024/74353374-7f1fb500-4dc2-11ea-934c-a117d0988cdd.png)

And the realms page
![2020-02-12_18 05 16](https://user-images.githubusercontent.com/33978024/74353416-8d6dd100-4dc2-11ea-94ab-2c21847940c1.png)

Both will likely still need textures from Monster.

**Comment by HIPPOKLEIDES** [comment]
Added Monster's new icons
