### ISSUE TITLE
Critical Bug - Lots of blocks had their textures replaced with acacia wood planks

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#5]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the bug**    
A large selection of blocks have acacia wood textures.

**Note**    
Use the attached world file for easy testing.
[Block_Preview_World.zip](https://github.com/Conquest-Reforged/Indev/files/4076237/Block_Preview_World.zip)

**Comment by dags-** [comment]
Most of a our generated blockstate/model jsons are derrived from the acacia equivalent, so this would suggest some of the CR blocks are being defined without a texture override being defined

**Comment by HIPPOKLEIDES** [comment]
Right now, the issue is that everything that uses a class with @Assets annotations, despite using Props.manual(), gets overridden with generated blockstates and models that use the acacia texture.

**Comment by dags-** [comment]
Think I traced it down to the 'manual' flag not being copied when cloning the Props object - this only happens for cutout/translucent blocks so I'm confused it affects everything with an Asset annotation, as suggested.

Could we check the latest build and confirm?
Obviously without a screenshot or any mention of specifc blocks I can't check for myself

**Comment by HIPPOKLEIDES** [comment]
Looks like it is fixed!
