### ISSUE TITLE
Painted wood blocks should be moved from painted tab to wood tab.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#50]

**Comment by HIPPOKLEIDES** [comment]
Appended these blocks to Advanced Carpentry tab

**Comment by CreativeRealms** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/33978024/73791226-93ecbf00-47aa-11ea-95a6-699dfb37a4b4.png)
Not fixed in build 64

**Comment by HIPPOKLEIDES** [comment]
Oops. Try build 65
