### ISSUE TITLE
Beam glitching at block bounds

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#51]
![2020-02-04_18 17 02](https://user-images.githubusercontent.com/33978024/73763799-9d5e3300-477a-11ea-9451-c458b634591a.png)

**Comment by CreativeRealms** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/33978024/73780564-5e8aa600-4797-11ea-89ba-fc83c0975d28.png)
Close up. It's more noticeable in-game.

**Comment by ArtemisiaTR** [comment]
Should be fixed in next build.
