### ISSUE TITLE
Thin shutters have missing textures/models depending on opened variant.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#54]
**Mod Version & Build Number**    
79

**Describe the bug**    
Thin shutters have missing textures/model breaks when opening/closing.

**Screenshots/Video**    
![2020-02-08_04 26 14](https://user-images.githubusercontent.com/33978024/74078032-0f11d780-4a2e-11ea-8b81-18eccf538fbe.png)
![2020-02-08_04 29 34](https://user-images.githubusercontent.com/33978024/74078035-1933d600-4a2e-11ea-8377-400d5ab80366.png)

**Comment by ArtemisiaTR** [comment]
![2020-02-08_12 52 04](https://user-images.githubusercontent.com/29824134/74083907-31314700-4a7a-11ea-9274-045d83718f50.png)
Sould be fixed now.
