### ISSUE TITLE
Organize advanced carpentry tab so all full blocks/shutters are together.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#55]
**Describe your suggestion**    
See title

![2020-02-08_04 26 58](https://user-images.githubusercontent.com/33978024/74078067-86476b80-4a2e-11ea-8f4e-48cc3fa89fa0.png)

**Comment by HIPPOKLEIDES** [comment]
To me, looks a lot better as it is now. I think it just starts to look messy when switching between models and full blocks

**Comment by CreativeRealms** [comment]
Could be you misinterpreted my request.
These shutters are near the top of the page:
![Screenshot_2](https://user-images.githubusercontent.com/33978024/74092772-5b622380-4ad1-11ea-97a8-272d74f1ee83.png)
And this one which is the same besides the paint is at the bottom:
![Screenshot_3](https://user-images.githubusercontent.com/33978024/74092779-792f8880-4ad1-11ea-80f7-ceed3b940276.png)

In addition the non painted shutters are also near the top:
![Screenshot_4](https://user-images.githubusercontent.com/33978024/74092783-8c425880-4ad1-11ea-847e-8faaa90e2dc9.png)
And the painted ones are all the way at the bottom:
![Screenshot_5](https://user-images.githubusercontent.com/33978024/74092788-995f4780-4ad1-11ea-80e7-718f58c0dbbc.png)

I just think they should be grouped together in the tab (not in the block picker GUI).

**Comment by HIPPOKLEIDES** [comment]
done build 88+
