### ISSUE TITLE
Remove vanilla carpets from creative menu and add to GUI (including carpets not in creative menu)

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#56]
![2020-02-08_04 32 34](https://user-images.githubusercontent.com/33978024/74078082-c0187200-4a2e-11ea-9149-2de7e150fb23.png)

**Comment by ArtemisiaTR** [comment]
I have sent missing carpet textures to monsterfish to check.

**Comment by CreativeRealms** [comment]
> I have sent missing carpet textures to monsterfish to check.

This bug has nothing to do with the textures.

**Comment by HIPPOKLEIDES** [comment]
Fixed in build 82+
