### ISSUE TITLE
All thin shutters glicthing when there is a full block behind them.

### ISSUE THREAD

**Issue by ArtemisiaTR** [Conquest-Reforged/Indev#58]
![2020-02-08_12 47 09](https://user-images.githubusercontent.com/29824134/74083857-9a648a80-4a79-11ea-8aa8-d23442a8ee36.png)

Only happening when they are on closed state.

Build-79.

Note: Probably happening because of hitbox since model is thinner now.

**Comment by HIPPOKLEIDES** [comment]
Fixed in build 82+
For future reference, when this happens it's usually just culling in the block model as it was in this case
