### ISSUE TITLE
Texture bug - Modded rails

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#6]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the bug**    
Custom rails chains/rope/planks have the vanilla rail texture overlayed on top of them.

**Comment by HIPPOKLEIDES** [comment]
fixed in build 29
