### ISSUE TITLE
Show a warning or some other visual notification when Optifine and/or the resourcepack are not installed/enabled.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#60]
**Describe your suggestion**    
See Title

**Comment by dags-** [comment]
Discussion: where should this be displayed and how obtrusive should it be?

My initial thought is to have a button show up on the main menu that takes you to a screen that lists the missing dependencies and has buttons that open urls to their download pages.

A rough example of the main menu:
![warn](https://user-images.githubusercontent.com/4276064/74142167-3adcbb00-4bf0-11ea-8ccb-d91d67ea6f7a.png)

This maybe needs some text next to the button saying something like 'missing dependencies!' (maybe make it only show up only when you hover over the button?)

**Comment by Monsterfisch** [comment]
I would almost argue its best to have it show up right after the Mojang screen as its own screen you could then tick a box to turn it off if you really don't want to get the dependencies. on that screen, We could then also show in a gif the visual difference as well. That way people don't just muscle memory like click past the extra button which has a chance to be overlooked/ignored. 
here is a rough sketch of what I am thinking https://i.imgur.com/RUM2wcB.png

**Comment by dags-** [comment]
Sur,e we can make it a splash screen. It'd need to be a static image rather than a gif though (there's no easy way to render gifs with minecraft's GUI code [that I'm aware of]). A side-by-side style image would do though right?

**Comment by Monsterfisch** [comment]
yup that would do the trick just fine hence i have it as a variant

**Comment by Monsterfisch** [comment]
here a pic for the comparing picture =) 
![optifine_you_should_get_it!](https://user-images.githubusercontent.com/24592166/74196926-9fcefa00-4c5e-11ea-9836-77103e59a181.png)

**Comment by dags-** [comment]
This feature has been added - TBD whether buttons link directly to the optifine/curse pages or a tutorial on cr.com

**Comment by CreativeRealms** [comment]
Request to add a config option to disable the resourcepack warning (while keeping the Optifine one) for modpacks that have the resourcepack installed and enabled by default to prevent confusion.

**Comment by dags-** [comment]
The UI only lists the missing dependencies (optifine if not present, the RP if not enabled).

The way RP detection works is by reading the file name of the pack. This isn't ideal, because the filename could easily be changed to anything (if downloaded directly from the repo, for example), and if we try to 'fuzzy match' it, it may detect to the vanilla conquest pack if the user has that installed mistakenly.

I think we might be able to add a custom entry in the `pack.mcmeta` file of the RP and use that for detetection instead

**Comment by CreativeRealms** [comment]
Maybe because it still shows up for me even when the RP is enabled.

**Comment by dags-** [comment]
Hopefully build#140 works better (you'll need to redownload the RP from the repo, or modify the pack.mcmeta [as updated here](https://github.com/HIPPOKLEIDES/Conquest-Reforged-Resourcepack/blob/1.14.x/pack.mcmeta))

**Comment by CreativeRealms** [comment]
Works now

**Comment by Monsterfisch** [comment]
We can definitely add a tag to the pack.mcmeta.
Afterall when the user has a pack in the download folder already the newer one tends to be renamed to pack (2).zip, which could in turn cause problems that way we can also add a version tag in the pack.mcmeta to make sure it notifies the user he/she is using the latest version of the pack.
