### ISSUE TITLE
Block picker GUI has broken for (seemingly all blocks) besides food bites.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#62]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-84-mc1.15.2

**Forge Version**    
1.15.2-forge-31.1.0

**Screenshots/Video**    
![Screenshot_1](https://user-images.githubusercontent.com/33978024/74092880-1212d380-4ad3-11ea-9af6-d7e2bbbbee1b.png)
![Screenshot_2](https://user-images.githubusercontent.com/33978024/74092881-14752d80-4ad3-11ea-855c-bf58e282a90b.png)

**Comment by dags-** [comment]
Note to self: probably this:
https://github.com/Conquest-Reforged/ReforgedMod/blob/master/ReforgedClient/src/main/java/com/conquestreforged/client/gui/palette/Palette.java#L39
