### ISSUE TITLE
Center-align bread plate's item model

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#63]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-84-mc1.15.2

**Forge Version**    
1.15.2-forge-31.1.0

**Screenshots/Video**  
![Screenshot_1](https://user-images.githubusercontent.com/33978024/74092928-bc8af680-4ad3-11ea-8afe-5ce8d3a4c79e.png)

**Comment by HIPPOKLEIDES** [comment]
fixed build 88+
