### ISSUE TITLE
Cut red sandstone not appearing properly in block picker GUI

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#68]
![Screenshot_1](https://user-images.githubusercontent.com/33978024/74987365-aff78e00-5443-11ea-88be-d6da190d066f.png)

**Comment by CreativeRealms** [comment]
In addition it does not appear to have any variants.

**Comment by dags-** [comment]
That's the debugging palette. When a block doesn't have a family it randomly generates a palette of random size and of random blocks. This is so I can easily test the gui with different looking items and varying numbers of them.

As to whether that particular block is supposed to have a family and variants I'm not sure.

**Comment by HIPPOKLEIDES** [comment]
fixed
smooth red sandstone was accidentally made the parent of the cut red sandstone variants
