### ISSUE TITLE
Moss, Lichen, and Bearberry have Acacia texture in hotbar/hand/inventory

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#69]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-102-mc1.15.2

**Screenshots/Video**    
![Screenshot_1](https://user-images.githubusercontent.com/33978024/75004348-70489a80-5473-11ea-9700-6617553a358b.png)

**Comment by HIPPOKLEIDES** [comment]
fixed
