### ISSUE TITLE
Tall seagrass has missing texture/large model in inventory/hotbar/hand and is not in the creative menu

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#70]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-102-mc1.15.2

**Screenshots/Video**    
![2020-02-21_06 31 04](https://user-images.githubusercontent.com/33978024/75004470-e2b97a80-5473-11ea-8a89-072f58ab1413.png)

**Comment by HIPPOKLEIDES** [comment]
fixed/added
