### ISSUE TITLE
Wood block picker bug GUI 

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#72]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-107-mc1.15.2

**Describe the bug**    
Full/Semi bark logs don't appear in block picker GUI together

**Screenshots/Video**    
![full wood vs semi full](https://user-images.githubusercontent.com/33978024/75081719-e05d2c00-5518-11ea-97fc-5ac19c60c3b7.png)

**Comment by HIPPOKLEIDES** [comment]
fixed/added
