### ISSUE TITLE
Circular arches do not have visible hitboxes

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#75]
**Screenshots/Video**    
![no hitbox](https://user-images.githubusercontent.com/33978024/75081811-4c3f9480-5519-11ea-98ec-1da4e95dca0f.png)

**Comment by HIPPOKLEIDES** [comment]
It's hidden by the model and is otherwise fully functional.
Could make it larger than the block bounds but that'll be awkward and buggy
