### ISSUE TITLE
Enhancement - Organize creative inventory and JEI

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#8]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-21-mc1.15.1-AllInOne

**Forge Version**    
forge-30.0.8

**Describe the suggestion**    
Reorganize creative tabs and block load order to make JEI neater.

![Screenshot_2](https://user-images.githubusercontent.com/33978024/72603383-95506780-3921-11ea-9aee-83b55cf931d5.png)
![Screenshot_1](https://user-images.githubusercontent.com/33978024/72603386-95506780-3921-11ea-8347-23c0ee84deb8.png)

**Comment by dags-** [comment]
I would like to make the arrangement of items in the creative tabs more customizable.

Currently it's sortof hard-coded in a somewhat arbitrary order (ie one that cannot be defined programmatically). My plan is to offer other forms of sorting as options to the end user (alphabetical would be one).

That said, I don't know JEI would sort according to the order of CreativeTabs and their contents.
Sorting of stuff displayed in JEI's GUI is outside of CR's scope unless there's some convention I don't know about.

**Comment by CreativeRealms** [comment]
> I would like to make the arrangement of items in the creative tabs more customizable.
> 
> Currently it's sortof hard-coded in a somewhat arbitrary order (ie one that cannot be defined programmatically). My plan is to offer other forms of sorting as options to the end user (alphabetical would be one).
> 
> That said, I don't know why JEI would sort according to the order of CreativeTabs and their contents.
> Sorting of stuff displayed in JEI's GUI is outside of CR's scope unless there's some convention I don't know about.

I think JEI sorts based on the order blocks were added to the mod. Most of it is organized besides the recent blocks which are all over the place.

**Comment by dags-** [comment]
Ah, yeah it's more likely that they're looping through the Block/Item registry than the CreativeTabs.
Sorting their results is up to them. Maybe they just haven't fully updated things to 1.15 yet

**Comment by CreativeRealms** [comment]
> Ah, yeah it's more likely that they're looping through the Block/Item registry than the CreativeTabs.
> Sorting their results is up to them. Maybe they just haven't fully updated things to 1.15 yet

Right which is why I thought sorting the block registry is something we could do on our end.

**Comment by dags-** [comment]
You can change the order that you register blocks in your own mod, but on our scale it wouldn't be practical or maintainable, and in general would not be reliable.
