### ISSUE TITLE
Add missing Conquest versions of vanilla bed types

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#82]
**Screenshots/Video**    
![add bed](https://user-images.githubusercontent.com/33978024/75082145-e94efd00-551a-11ea-90ce-615f9e702044.png)

**Comment by HIPPOKLEIDES** [comment]
Added them as new Conquest blocks for improved rendering.
Monster will make the vanilla beds simply different colors of the basic red bed.
