### ISSUE TITLE
Slight GUI changes to Optifine/Resourcepack warning

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#85]
**What to Change**    
-The picture showing Optifine on/off seems to have been downscaled and is very pixelated. If possible add a higher res image
-The black background behind the buttons should be removed
-The width of the Optifine/Resourcepack buttons should be reduced by about half 

**Screenshots/Video**    
![2020-02-22_19 03 35](https://user-images.githubusercontent.com/33978024/75096243-5d82b280-55a6-11ea-9b2e-db58e0f5b249.png)

**Comment by dags-** [comment]
- the image no longer scales above it's native resolution
- buttons are sized to fit the longest text + a small amount of padding

**Comment by CreativeRealms** [comment]
Black outline is still in the background (highlighted in red) and the OF image is still pixelated. (build 112)

![2020-02-22_20 05 11](https://user-images.githubusercontent.com/33978024/75097071-046b4c80-55af-11ea-97f9-dde1e2d2bcac.png)

**Comment by dags-** [comment]
The shadow effect is fine.

Large gui scales will make the image look more pixellated. It serves its purpose as-is. No point adding bulk to the jar (higher res images) for something that users won't ever see 99% of the time.

**Comment by Monsterfisch** [comment]
whats the pixel resolution on the image you have currently? since I could just make one that's better suited for the resolution as for the "shadow" have it start at the bottom of the image so there is no gab in between the two elements than it will look more deliberate instead of two floating elements

**Comment by dags-** [comment]
The image is 432x256. Where do you propose the list title go?

**Comment by Monsterfisch** [comment]
sorta like this https://i.imgur.com/1dyID2K.png

**Comment by Monsterfisch** [comment]
![optifine_you_should_get_it!](https://user-images.githubusercontent.com/24592166/75100370-fb897380-55cc-11ea-8f43-4bb88b739431.png)
heres an updated version of the image =)
