### ISSUE TITLE
Alpha Release System

### ISSUE THREAD

**Issue by dags-** [Conquest-Reforged/Indev#86]
I'm planning on setting up another build task for the mod (that the patrons will have access to) which will only build new jars on tagged commits:

- allows us to manually schedule updates to users rather than the rolling release system we use internally
- avoids a flustercuck of users reporting different issues specific to different builds
- the 'instant' builds used by the dev team occasionally (often) get debugging code left in which may cause confusion for end users. We can QC the state of the mod repo before publishing to patrons

(The builds will still be accessible through the auth-protected ci site - just at a different path)

**Comment by CreativeRealms** [comment]
How would this work for things like giveaways or distribution to non donators (like YouTubers and stuff)? Should we just give them a specific build (much easier option but they don't get all the builds) or maybe add a rank for them on Discord (would be an issue for people not in our Discord)?

**Comment by dags-** [comment]
Both options are fine by me. A discord role should be the primary way, with distributing manually being the fallback
