### ISSUE TITLE
Campfire missing texture

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#88]
**Mod Version & Build Number**    
ConquestReforged-4.0.0-121-mc1.15.2

**Screenshots/Video**    
![2020-02-26_17 46 12](https://user-images.githubusercontent.com/33978024/75361487-08a1ad80-58c0-11ea-99b3-5f08bf3ec017.png)

**Comment by ArtemisiaTR** [comment]
Fixed.
