### ISSUE TITLE
Cut cheese has missing textures/models

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#89]
**Screenshots/Video**    
![Screenshot_1](https://user-images.githubusercontent.com/33978024/75477486-167d2e80-59a5-11ea-9ae3-a0afe1d73b9f.png)
![2020-02-27_00 15 49](https://user-images.githubusercontent.com/33978024/75477589-390f4780-59a5-11ea-9941-46e83961b9df.png)

**Comment by dags-** [comment]
missing underscore in the item model json
