### ISSUE TITLE
Critical Bug - Trees are not spawning in various biomes

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#9]
**Mod Version & Build Number**    
TerraForged-0.0.1-ALPHA-9-mc1.15.1

**Forge Version**    
forge-1.15.1-30.0.8

**Describe the bug**    
Trees are not appearing in various biomes. Sometimes a few trees will spawn but not in the proper quantity.

![2020-01-17_13 05 40](https://user-images.githubusercontent.com/33978024/72609415-7fe13a80-392d-11ea-93f0-009cf4c5b3f5.png)
![2020-01-17_13 06 44](https://user-images.githubusercontent.com/33978024/72609417-7fe13a80-392d-11ea-82fb-3e7b2d838366.png)
![2020-01-17_13 08 41](https://user-images.githubusercontent.com/33978024/72609418-8079d100-392d-11ea-9b36-5993c18327c1.png)
![2020-01-17_13 11 28](https://user-images.githubusercontent.com/33978024/72609419-8079d100-392d-11ea-972f-f9afa05b985c.png)
![2020-01-17_13 15 18](https://user-images.githubusercontent.com/33978024/72609420-81126780-392d-11ea-8370-e4ecaa108f04.png)

**Comment by dags-** [comment]
I never came across this myself but please try builds 15 and above. This includes a large change to TF's feature management system which hopefully has ironed out any kinks from the initial 1.15 port

**Comment by CreativeRealms** [comment]
> I never came across this myself but please try builds 15 and above. This includes a large change to TF's feature management system which hopefully has ironed out any kinks from the initial 1.15 port

Still not fixed in the latest version.

**Comment by CreativeRealms** [comment]
Also noticed this. Kind of doubt bamboo is supposed to be spawning on sand.

![2020-01-17_15 12 37](https://user-images.githubusercontent.com/33978024/72614895-174d8a00-393c-11ea-990f-e193779e4894.png)

**Comment by dags-** [comment]
Yeah I think that's an area that should have been changed to a beach biome but has been left as jungle. Should be a simple fix

**Comment by dags-** [comment]
All's working as intended

**Comment by CreativeRealms** [comment]
TerraForged-0.0.1-22-mc1.15.1
Dark forest doesn't spawn.
![2020-01-20_09 23 03](https://user-images.githubusercontent.com/33978024/72706384-90c8c080-3b66-11ea-82b5-04a8e2f630af.png)

**Comment by dags-** [comment]
That's the treeline taking effect
