### ISSUE TITLE
Campfire has no light

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#90]
**Screenshots/Video**    
![2020-02-27_20 21 30](https://user-images.githubusercontent.com/33978024/75477662-56441600-59a5-11ea-8caa-ff966b05b8a8.png)

**Comment by dags-** [comment]
gave it the same light level as vanilla campfires

**Comment by CreativeRealms** [comment]
Shouldn't it work the same way as Conquest lighting blocks?

**Comment by dags-** [comment]
It just inherits properties from the vanilla block, so doesn't have a light level property like CR's torches etc.

Seems like too big a flame for it to make sense having dimmer versions of it - to me, at least - but I'm not too fussed about what's added or not.

It's worth keeping in mind that each light level would increase the number of blockstates by a _lot_
