### ISSUE TITLE
Conquest bee hive/hornets nest can be walked through and have plant sounds

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#96]
**Screenshots/Video**    
![2020-02-28_12 29 55](https://user-images.githubusercontent.com/33978024/75541213-2be66d00-5a26-11ea-8542-17c4790b61f4.png)

**Comment by dags-** [comment]
Rope variant now inherits sound from cloth (same as other rope blocks)

The other variant has wood sound (same as vanilla hive)
