### ISSUE TITLE
Vanilla stone stair/slab variants do not show up in the GUI

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#98]
**Screenshots/Video**    
![Screenshot_1](https://user-images.githubusercontent.com/33978024/75626317-49a30600-5bcf-11ea-962f-cadc2b946b69.png)

**Comment by dags-** [comment]
Added

**Comment by CreativeRealms** [comment]
Stairs still do not appear when selecting a full stone block.

ConquestReforged-mc1.15.2-4.0.0-135

![Screenshot_1](https://user-images.githubusercontent.com/33978024/75645548-f96b8880-5c4e-11ea-8355-ce1479236a23.png)

**Comment by dags-** [comment]
Oh, seems I didn't push the changes to the Content module. I'll get on that this evening

**Comment by dags-** [comment]
Nvm, did push them but didn't update the reference in the main repo. Fixed
